/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hospital.ui;

import com.hospital.models.*;
import com.hospital.utils.DataStore;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author lenovo
 */
public class AdminDashboard extends javax.swing.JFrame {

    private String username;
    private DataStore dataStore;

    public AdminDashboard(String username) {
        this.username = username;
        this.dataStore = DataStore.getInstance();
        initComponents();
        setLocationRelativeTo(null);
        lblWelcome.setText("Welcome, " + username);
        loadAllData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelReservations = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblReservations = new javax.swing.JTable();
        btnApproveReservation = new javax.swing.JButton();
        btnDeclineReservation = new javax.swing.JButton();
        btnRefreshReservations = new javax.swing.JButton();
        panelBilling = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblBilling = new javax.swing.JTable();
        btnAddBilling = new javax.swing.JButton();
        btnEditBilling = new javax.swing.JButton();
        btnMarkPaid = new javax.swing.JButton();
        btnRefreshBilling = new javax.swing.JButton();
        panelSignup = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSignup = new javax.swing.JTable();
        btnApproveSignup = new javax.swing.JButton();
        btnRejectSignup = new javax.swing.JButton();
        btnRefreshSignup = new javax.swing.JButton();
        panelUsers = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnAddUser = new javax.swing.JButton();
        btnEditUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnRefreshUsers = new javax.swing.JButton();
        panelRooms = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRooms = new javax.swing.JTable();
        btnAddRoom = new javax.swing.JButton();
        btnEditRoom = new javax.swing.JButton();
        btnDeleteRoom = new javax.swing.JButton();
        btnRefreshRooms = new javax.swing.JButton();
        panelPatients = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPatients = new javax.swing.JTable();
        btnAddPatient = new javax.swing.JButton();
        btnEditPatient = new javax.swing.JButton();
        btnDeletePatient = new javax.swing.JButton();
        btnRefreshPatients = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 850));
        jPanel1.setPreferredSize(new java.awt.Dimension(1005, 850));

        jTabbedPane1.setForeground(new java.awt.Color(0, 204, 204));
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1000, 700));

        panelReservations.setPreferredSize(new java.awt.Dimension(1000, 700));

        tblReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Patient ID", "Type", "Doctor", "Date", "Status", "Notes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblReservations);

        btnApproveReservation.setBackground(new java.awt.Color(0, 204, 51));
        btnApproveReservation.setText("Approve");
        btnApproveReservation.setPreferredSize(new java.awt.Dimension(92, 63));
        btnApproveReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveReservationActionPerformed(evt);
            }
        });

        btnDeclineReservation.setBackground(new java.awt.Color(255, 51, 0));
        btnDeclineReservation.setText("Decline");
        btnDeclineReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineReservationActionPerformed(evt);
            }
        });

        btnRefreshReservations.setBackground(new java.awt.Color(0, 204, 51));
        btnRefreshReservations.setText("Refresh");
        btnRefreshReservations.setPreferredSize(new java.awt.Dimension(92, 63));
        btnRefreshReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshReservationsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReservationsLayout = new javax.swing.GroupLayout(panelReservations);
        panelReservations.setLayout(panelReservationsLayout);
        panelReservationsLayout.setHorizontalGroup(
            panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservationsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApproveReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeclineReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefreshReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelReservationsLayout.setVerticalGroup(
            panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeclineReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApproveReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(278, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reservations", panelReservations);

        panelBilling.setPreferredSize(new java.awt.Dimension(1000, 700));

        tblBilling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Bill ID", "Patient ID", "Description", "Amount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblBilling);

        btnAddBilling.setBackground(new java.awt.Color(0, 204, 255));
        btnAddBilling.setText("Add");
        btnAddBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBillingActionPerformed(evt);
            }
        });

        btnEditBilling.setBackground(new java.awt.Color(255, 153, 0));
        btnEditBilling.setText("Edit");
        btnEditBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBillingActionPerformed(evt);
            }
        });

        btnMarkPaid.setBackground(new java.awt.Color(0, 204, 51));
        btnMarkPaid.setText("Mark Paid");
        btnMarkPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkPaidActionPerformed(evt);
            }
        });

        btnRefreshBilling.setBackground(new java.awt.Color(0, 204, 102));
        btnRefreshBilling.setText("Refresh");
        btnRefreshBilling.setPreferredSize(new java.awt.Dimension(92, 63));

        javax.swing.GroupLayout panelBillingLayout = new javax.swing.GroupLayout(panelBilling);
        panelBilling.setLayout(panelBillingLayout);
        panelBillingLayout.setHorizontalGroup(
            panelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBillingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMarkPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefreshBilling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBillingLayout.setVerticalGroup(
            panelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshBilling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMarkPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(308, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Billing", panelBilling);

        panelSignup.setPreferredSize(new java.awt.Dimension(1000, 700));

        tblSignup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblSignup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Email", "Phone", "Address", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSignup.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblSignup);

        btnApproveSignup.setBackground(new java.awt.Color(0, 204, 51));
        btnApproveSignup.setText("Approve");
        btnApproveSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveSignupActionPerformed(evt);
            }
        });

        btnRejectSignup.setBackground(new java.awt.Color(255, 51, 51));
        btnRejectSignup.setText("Reject");
        btnRejectSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectSignupActionPerformed(evt);
            }
        });

        btnRefreshSignup.setBackground(new java.awt.Color(0, 204, 0));
        btnRefreshSignup.setText("Refresh");

        javax.swing.GroupLayout panelSignupLayout = new javax.swing.GroupLayout(panelSignup);
        panelSignup.setLayout(panelSignupLayout);
        panelSignupLayout.setHorizontalGroup(
            panelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
            .addGroup(panelSignupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApproveSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRejectSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefreshSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSignupLayout.setVerticalGroup(
            panelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApproveSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRejectSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(332, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Signup Requests", panelSignup);

        panelUsers.setPreferredSize(new java.awt.Dimension(1000, 700));

        jScrollPane6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblUsers);

        btnAddUser.setBackground(new java.awt.Color(0, 204, 255));
        btnAddUser.setText("Add");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnEditUser.setBackground(new java.awt.Color(255, 153, 0));
        btnEditUser.setText("Edit");
        btnEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserActionPerformed(evt);
            }
        });

        btnDeleteUser.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteUser.setText("Delete");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnRefreshUsers.setBackground(new java.awt.Color(0, 204, 51));
        btnRefreshUsers.setText("Refresh");
        btnRefreshUsers.setPreferredSize(new java.awt.Dimension(92, 63));

        javax.swing.GroupLayout panelUsersLayout = new javax.swing.GroupLayout(panelUsers);
        panelUsers.setLayout(panelUsersLayout);
        panelUsersLayout.setHorizontalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefreshUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelUsersLayout.setVerticalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRefreshUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEditUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Users", panelUsers);

        panelRooms.setPreferredSize(new java.awt.Dimension(1000, 700));

        tblRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room No", "Patient ID", "Status", "Cleaner", "Cleaning Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblRooms);

        btnAddRoom.setBackground(new java.awt.Color(0, 204, 255));
        btnAddRoom.setText("Add");
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });

        btnEditRoom.setBackground(new java.awt.Color(255, 102, 0));
        btnEditRoom.setText("Edit");
        btnEditRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRoomActionPerformed(evt);
            }
        });

        btnDeleteRoom.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteRoom.setText("Delete");
        btnDeleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRoomActionPerformed(evt);
            }
        });

        btnRefreshRooms.setBackground(new java.awt.Color(0, 204, 102));
        btnRefreshRooms.setText("Refresh");
        btnRefreshRooms.setPreferredSize(new java.awt.Dimension(92, 63));

        javax.swing.GroupLayout panelRoomsLayout = new javax.swing.GroupLayout(panelRooms);
        panelRooms.setLayout(panelRoomsLayout);
        panelRoomsLayout.setHorizontalGroup(
            panelRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoomsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefreshRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRoomsLayout.setVerticalGroup(
            panelRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoomsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRefreshRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEditRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rooms", panelRooms);

        panelPatients.setMinimumSize(new java.awt.Dimension(1000, 700));
        panelPatients.setPreferredSize(new java.awt.Dimension(1000, 700));

        tblPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Status", "Disease", "Doctor", "Room", "Bill"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPatients);

        btnAddPatient.setBackground(new java.awt.Color(0, 204, 255));
        btnAddPatient.setText("Add");
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });

        btnEditPatient.setBackground(new java.awt.Color(255, 153, 0));
        btnEditPatient.setText("Edit");
        btnEditPatient.setPreferredSize(new java.awt.Dimension(92, 63));
        btnEditPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPatientActionPerformed(evt);
            }
        });

        btnDeletePatient.setBackground(new java.awt.Color(255, 51, 51));
        btnDeletePatient.setText("Delete");
        btnDeletePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePatientActionPerformed(evt);
            }
        });

        btnRefreshPatients.setBackground(new java.awt.Color(0, 204, 51));
        btnRefreshPatients.setText("Refresh");
        btnRefreshPatients.setPreferredSize(new java.awt.Dimension(92, 63));

        javax.swing.GroupLayout panelPatientsLayout = new javax.swing.GroupLayout(panelPatients);
        panelPatients.setLayout(panelPatientsLayout);
        panelPatientsLayout.setHorizontalGroup(
            panelPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPatientsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshPatients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelPatientsLayout.setVerticalGroup(
            panelPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPatientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshPatients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(355, 355, 355))
        );

        jTabbedPane1.addTab("Patients", panelPatients);

        btnLogout.setBackground(new java.awt.Color(255, 51, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Admin Dashboard");

        lblWelcome.setBackground(new java.awt.Color(255, 255, 255));
        lblWelcome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 204, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome, Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 917, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to logout?",
            "Confirm Logout", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDeleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRoomActionPerformed
        int selectedRow = tblRooms.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a room to delete",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String roomNumber = (String) tblRooms.getValueAt(selectedRow, 0);

        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete room " + roomNumber + "?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            Room toRemove = null;
            for (Room r : dataStore.getRooms()) {
                if (r.getRoomNumber().equals(roomNumber)) {
                    toRemove = r;
                    break;
                }
            }

            if (toRemove != null) {
                dataStore.getRooms().remove(toRemove);
                loadRoomsData();
                JOptionPane.showMessageDialog(this, "Room deleted successfully",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteRoomActionPerformed

    private void btnEditRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRoomActionPerformed
        int selectedRow = tblRooms.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a room to edit",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String roomNumber = (String) tblRooms.getValueAt(selectedRow, 0);

        Room room = null;
        for (Room r : dataStore.getRooms()) {
            if (r.getRoomNumber().equals(roomNumber)) {
                room = r;
                break;
            }
        }

        if (room == null) return;

        JComboBox<String> cmbStatus = new JComboBox<String>(
            new String[]{"Available", "Unavailable", "Reserved"});
        cmbStatus.setSelectedItem(room.getStatus());
        JTextField txtCleaner = new JTextField(room.getAssignedCleaner(), 20);
        JComboBox<String> cmbCleanStatus = new JComboBox<String>(
            new String[]{"Clean", "Not Cleaned", "Need Repair"});
        cmbCleanStatus.setSelectedItem(room.getCleaningStatus());

        JPanel panel = new JPanel(new java.awt.GridLayout(3, 2, 5, 5));
        panel.add(new JLabel("Status:"));
        panel.add(cmbStatus);
        panel.add(new JLabel("Assigned Cleaner:"));
        panel.add(txtCleaner);
        panel.add(new JLabel("Cleaning Status:"));
        panel.add(cmbCleanStatus);

        int result = JOptionPane.showConfirmDialog(this, panel, "Edit Room: " + roomNumber,
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            room.setStatus((String) cmbStatus.getSelectedItem());
            room.setAssignedCleaner(txtCleaner.getText().trim());
            room.setCleaningStatus((String) cmbCleanStatus.getSelectedItem());

            loadRoomsData();
            JOptionPane.showMessageDialog(this, "Room updated successfully!",
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEditRoomActionPerformed

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        JTextField txtRoomNumber = new JTextField(20);
        JComboBox<String> cmbStatus = new JComboBox<String>(
            new String[]{"Available", "Unavailable", "Reserved"});
        JTextField txtCleaner = new JTextField(20);
        JComboBox<String> cmbCleanStatus = new JComboBox<String>(
            new String[]{"Clean", "Not Cleaned", "Need Repair"});

        JPanel panel = new JPanel(new java.awt.GridLayout(4, 2, 5, 5));
        panel.add(new JLabel("Room Number:"));
        panel.add(txtRoomNumber);
        panel.add(new JLabel("Status:"));
        panel.add(cmbStatus);
        panel.add(new JLabel("Assigned Cleaner:"));
        panel.add(txtCleaner);
        panel.add(new JLabel("Cleaning Status:"));
        panel.add(cmbCleanStatus);

        int result = JOptionPane.showConfirmDialog(this, panel, "Add New Room",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            String roomNum = txtRoomNumber.getText().trim();
            String status = (String) cmbStatus.getSelectedItem();
            String cleaner = txtCleaner.getText().trim();
            String cleanStatus = (String) cmbCleanStatus.getSelectedItem();

            if (roomNum.isEmpty() || cleaner.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all fields",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check if room already exists
            for (Room r : dataStore.getRooms()) {
                if (r.getRoomNumber().equals(roomNum)) {
                    JOptionPane.showMessageDialog(this, "Room already exists",
                        "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            Room newRoom = new Room(roomNum, null, status, cleaner, cleanStatus);
            dataStore.getRooms().add(newRoom);
            loadRoomsData();
            JOptionPane.showMessageDialog(this, "Room added successfully!",
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        int selectedRow = tblUsers.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user to delete",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String username = (String) tblUsers.getValueAt(selectedRow, 0);

        // Cannot delete Admin or current user
        if (username.equals("Admin")) {
            JOptionPane.showMessageDialog(this, "Cannot delete Admin account",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (username.equals(this.username)) {
            JOptionPane.showMessageDialog(this, "Cannot delete your own account",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete user " + username + "?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            User toRemove = null;
            for (User u : dataStore.getUsers()) {
                if (u.getUsername().equals(username)) {
                    toRemove = u;
                    break;
                }
            }

            if (toRemove != null) {
                dataStore.getUsers().remove(toRemove);
                loadUsersData();
                JOptionPane.showMessageDialog(this, "User deleted successfully",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        int selectedRow = tblUsers.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user to edit",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String username = (String) tblUsers.getValueAt(selectedRow, 0);

        // Cannot edit Admin account
        if (username.equals("Admin")) {
            JOptionPane.showMessageDialog(this, "Cannot edit Admin account",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        User user = null;
        for (User u : dataStore.getUsers()) {
            if (u.getUsername().equals(username)) {
                user = u;
                break;
            }
        }

        if (user == null) return;

        JPasswordField txtPassword = new JPasswordField(20);
        JComboBox<String> cmbRole = new JComboBox<String>(
            new String[]{"CO_ADMIN", "DOCTOR", "NURSE", "CASHIER"});
        cmbRole.setSelectedItem(user.getRole());

        JPanel panel = new JPanel(new java.awt.GridLayout(2, 2, 5, 5));
        panel.add(new JLabel("New Password:"));
        panel.add(txtPassword);
        panel.add(new JLabel("Role:"));
        panel.add(cmbRole);

        int result = JOptionPane.showConfirmDialog(this, panel, "Edit User: " + username,
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            String newPassword = new String(txtPassword.getPassword());
            if (!newPassword.isEmpty()) {
                user.setPassword(newPassword);
            }
            user.setRole((String) cmbRole.getSelectedItem());

            loadUsersData();
            JOptionPane.showMessageDialog(this, "User updated successfully!",
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        JTextField txtUsername = new JTextField(20);
        JPasswordField txtPassword = new JPasswordField(20);
        JComboBox<String> cmbRole = new JComboBox<String>(
            new String[]{"CO_ADMIN", "DOCTOR", "NURSE", "CASHIER"});

        JPanel panel = new JPanel(new java.awt.GridLayout(3, 2, 5, 5));
        panel.add(new JLabel("Username:"));
        panel.add(txtUsername);
        panel.add(new JLabel("Password:"));
        panel.add(txtPassword);
        panel.add(new JLabel("Role:"));
        panel.add(cmbRole);

        int result = JOptionPane.showConfirmDialog(this, panel, "Add New User",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            String username = txtUsername.getText().trim();
            String password = new String(txtPassword.getPassword());
            String role = (String) cmbRole.getSelectedItem();

            if (username.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all fields",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check if username exists
            for (User u : dataStore.getUsers()) {
                if (u.getUsername().equals(username)) {
                    JOptionPane.showMessageDialog(this, "Username already exists",
                        "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            User newUser = new User(username, password, role);
            dataStore.getUsers().add(newUser);
            loadUsersData();
            JOptionPane.showMessageDialog(this, "User added successfully!",
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnRejectSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectSignupActionPerformed

        int selectedRow = tblSignup.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a signup request", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to reject this signup?",
            "Confirm", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        String username = (String) tblSignup.getValueAt(selectedRow, 4);

        Signup toRemove = null;
        for (Signup s : dataStore.getSignup()) {
            if (s.getUsername().equals(username) && s.getPatientId() == null) {
                toRemove = s;
                break;
            }
        }

        if (toRemove != null) {
            dataStore.getSignup().remove(toRemove);
            JOptionPane.showMessageDialog(this, "Signup rejected", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadSignupData();
        }
    }//GEN-LAST:event_btnRejectSignupActionPerformed

    private void btnApproveSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveSignupActionPerformed

        int selectedRow = tblSignup.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a signup request", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String username = (String) tblSignup.getValueAt(selectedRow, 4);

        Signup signup = null;
        for (Signup s : dataStore.getSignup()) {
            if (s.getUsername().equals(username) && s.getPatientId() == null) {
                signup = s;
                break;
            }
        }

        if (signup == null) return;

        // Get patient details via dialogs
        String[] statusOptions = {"Outpatient", "Inpatient"};
        String patientStatus = (String) JOptionPane.showInputDialog(this,
            "Select Patient Status:", "Approve Signup",
            JOptionPane.QUESTION_MESSAGE, null, statusOptions, statusOptions[0]);

        if (patientStatus == null) return;

        String doctor = JOptionPane.showInputDialog(this, "Assign Doctor (username):", "dr.juan");
        if (doctor == null) return;

        String room = null;
        if (patientStatus.equals("Inpatient")) {
            room = JOptionPane.showInputDialog(this, "Assign Room:", "R101");
        }

        // Generate Patient ID
        String patientId = "P" + String.format("%03d", dataStore.getPatients().size() + 1);

        // Update signup
        signup.setPatientId(patientId);
        signup.setPatientStatus(patientStatus);
        signup.setAssignedDoctor(doctor);
        signup.setAssignedRoom(room);

        // Create patient record
        Patient newPatient = new Patient(
            patientId,
            signup.getFullName(),
            signup.getEmail(),
            signup.getPhone(),
            patientStatus,
            "Not Diagnosed",
            "Checked In",
            doctor,
            room,
            0.0
        );
        dataStore.getPatients().add(newPatient);

        JOptionPane.showMessageDialog(this, "Signup approved!", "Success", JOptionPane.INFORMATION_MESSAGE);
        loadSignupData();
        loadPatientsData();
    }//GEN-LAST:event_btnApproveSignupActionPerformed

    private void btnMarkPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkPaidActionPerformed
        int selectedRow = tblBilling.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a billing to mark as paid",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String billId = (String) tblBilling.getValueAt(selectedRow, 0);

        for (Billing b : dataStore.getBillings()) {
            if (b.getBillingId().equals(billId)) {
                b.setStatus("Paid");
                break;
            }
        }

        loadBillingData();
        JOptionPane.showMessageDialog(this, "Billing marked as paid",
            "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnMarkPaidActionPerformed

    private void btnEditBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBillingActionPerformed
        int selectedRow = tblBilling.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a billing to edit",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String billId = (String) tblBilling.getValueAt(selectedRow, 0);

        Billing billing = null;
        for (Billing b : dataStore.getBillings()) {
            if (b.getBillingId().equals(billId)) {
                billing = b;
                break;
            }
        }

        if (billing == null) return;

        JTextField txtDescription = new JTextField(billing.getDescription(), 20);
        JTextField txtAmount = new JTextField(String.valueOf(billing.getAmount()), 20);
        JComboBox<String> cmbStatus = new JComboBox<String>(new String[]{"Unpaid", "Paid"});
        cmbStatus.setSelectedItem(billing.getStatus());

        JPanel panel = new JPanel(new java.awt.GridLayout(3, 2, 5, 5));
        panel.add(new JLabel("Description:"));
        panel.add(txtDescription);
        panel.add(new JLabel("Amount:"));
        panel.add(txtAmount);
        panel.add(new JLabel("Status:"));
        panel.add(cmbStatus);

        int result = JOptionPane.showConfirmDialog(this, panel, "Edit Billing: " + billId,
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            try {
                billing.setDescription(txtDescription.getText().trim());
                billing.setAmount(Double.parseDouble(txtAmount.getText().trim()));
                billing.setStatus((String) cmbStatus.getSelectedItem());

                loadBillingData();
                JOptionPane.showMessageDialog(this, "Billing updated successfully!",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error updating billing: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditBillingActionPerformed

    private void btnAddBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBillingActionPerformed
        JTextField txtPatientId = new JTextField(20);
        JTextField txtDescription = new JTextField(20);
        JTextField txtAmount = new JTextField(20);
        JComboBox<String> cmbStatus = new JComboBox<String>(new String[]{"Unpaid", "Paid"});

        JPanel panel = new JPanel(new java.awt.GridLayout(4, 2, 5, 5));
        panel.add(new JLabel("Patient ID:"));
        panel.add(txtPatientId);
        panel.add(new JLabel("Description:"));
        panel.add(txtDescription);
        panel.add(new JLabel("Amount:"));
        panel.add(txtAmount);
        panel.add(new JLabel("Status:"));
        panel.add(cmbStatus);

        int result = JOptionPane.showConfirmDialog(this, panel, "Add New Billing",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            String patientId = txtPatientId.getText().trim();
            String description = txtDescription.getText().trim();
            String status = (String) cmbStatus.getSelectedItem();

            if (patientId.isEmpty() || description.isEmpty() || txtAmount.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all fields",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double amount;
            try {
                amount = Double.parseDouble(txtAmount.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid amount",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Verify patient exists
            boolean patientExists = false;
            for (Patient p : dataStore.getPatients()) {
                if (p.getPatientId().equals(patientId)) {
                    patientExists = true;
                    break;
                }
            }

            if (!patientExists) {
                JOptionPane.showMessageDialog(this, "Patient ID not found",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String billId = "BILL" + String.format("%03d", dataStore.getBillings().size() + 1);

            Billing newBilling = new Billing(billId, patientId, description, amount, status);
            dataStore.getBillings().add(newBilling);
            loadBillingData();
            JOptionPane.showMessageDialog(this, "Billing added successfully!",
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddBillingActionPerformed

    private void btnRefreshReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshReservationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshReservationsActionPerformed

    private void btnDeclineReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineReservationActionPerformed
        int selectedRow = tblReservations.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a reservation",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String resId = (String) tblReservations.getValueAt(selectedRow, 0);
        String reason = JOptionPane.showInputDialog(this, "Reason for declining:", "");

        if (reason != null) {
            for (Reservation r : dataStore.getReservations()) {
                if (r.getReservationId().equals(resId)) {
                    r.setStatus("Declined");
                    r.setNotes(reason);
                    break;
                }
            }

            loadReservationsData();
            JOptionPane.showMessageDialog(this, "Reservation declined",
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeclineReservationActionPerformed

    private void btnApproveReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveReservationActionPerformed
        int selectedRow = tblReservations.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a reservation",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String resId = (String) tblReservations.getValueAt(selectedRow, 0);

        for (Reservation r : dataStore.getReservations()) {
            if (r.getReservationId().equals(resId)) {
                r.setStatus("Approved");
                String notes = JOptionPane.showInputDialog(this, "Add notes (optional):", "");
                if (notes != null) {
                    r.setNotes(notes);
                }
                break;
            }
        }

        loadReservationsData();
        JOptionPane.showMessageDialog(this, "Reservation approved",
            "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnApproveReservationActionPerformed

    private void btnDeletePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePatientActionPerformed
        int selectedRow = tblPatients.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a patient to delete",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String patientId = (String) tblPatients.getValueAt(selectedRow, 0);

        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete patient " + patientId + "?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            Patient toRemove = null;
            for (Patient p : dataStore.getPatients()) {
                if (p.getPatientId().equals(patientId)) {
                    toRemove = p;
                    break;
                }
            }

            if (toRemove != null) {
                dataStore.getPatients().remove(toRemove);
                loadPatientsData();
                JOptionPane.showMessageDialog(this, "Patient deleted successfully",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeletePatientActionPerformed

    private void btnEditPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPatientActionPerformed
        int selectedRow = tblPatients.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a patient to edit",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String patientId = (String) tblPatients.getValueAt(selectedRow, 0);

        // Find patient
        Patient patient = null;
        for (Patient p : dataStore.getPatients()) {
            if (p.getPatientId().equals(patientId)) {
                patient = p;
                break;
            }
        }

        if (patient == null) return;

        // Pre-fill dialog with current values
        JTextField txtName = new JTextField(patient.getFullName(), 20);
        JTextField txtEmail = new JTextField(patient.getEmail(), 20);
        JTextField txtPhone = new JTextField(patient.getPhone(), 20);
        JComboBox<String> cmbStatus = new JComboBox<String>(new String[]{"Outpatient", "Inpatient","Checked In", "Discharged", "Under Treatment"});
        cmbStatus.setSelectedItem(patient.getPatientStatus());
        JTextField txtDisease = new JTextField(patient.getDisease(), 20);
        JTextField txtDoctor = new JTextField(patient.getAssignedDoctor(), 20);
        JTextField txtRoom = new JTextField(patient.getAssignedRoom() != null ? patient.getAssignedRoom() : "", 20);
        JTextField txtBill = new JTextField(String.valueOf(patient.getBill()), 20);
       // JComboBox<String> cmbPatientStatus = new JComboBox<String>(
           // new String[]{"Checked In", "Discharged", "Under Treatment"});
        //cmbPatientStatus.setSelectedItem(patient.getStatus());

        JPanel panel = new JPanel(new java.awt.GridLayout(9, 2, 5, 5));
        panel.add(new JLabel("Full Name:"));
        panel.add(txtName);
        panel.add(new JLabel("Email:"));
        panel.add(txtEmail);
        panel.add(new JLabel("Phone:"));
        panel.add(txtPhone);
        panel.add(new JLabel("Type:"));
        panel.add(cmbStatus);
        panel.add(new JLabel("Disease:"));
        panel.add(txtDisease);
       // panel.add(new JLabel("Status:"));
       //panel.add(cmbPatientStatus);
        panel.add(new JLabel("Doctor:"));
        panel.add(txtDoctor);
        panel.add(new JLabel("Room:"));
        panel.add(txtRoom);
        panel.add(new JLabel("Bill:"));
        panel.add(txtBill);

        int result = JOptionPane.showConfirmDialog(this, panel, "Edit Patient",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            try {
                patient.setFullName(txtName.getText().trim());
                patient.setEmail(txtEmail.getText().trim());
                patient.setPhone(txtPhone.getText().trim());
                patient.setPatientStatus((String) cmbStatus.getSelectedItem());
                patient.setDisease(txtDisease.getText().trim());
                //patient.setStatus((String) cmbPatientStatus.getSelectedItem());
                patient.setAssignedDoctor(txtDoctor.getText().trim());
                patient.setAssignedRoom(txtRoom.getText().trim());
                patient.setBill(Double.parseDouble(txtBill.getText().trim()));

                loadPatientsData();
                JOptionPane.showMessageDialog(this, "Patient updated successfully!",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error updating patient: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditPatientActionPerformed

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed
        // Create dialog for patient input
        JTextField txtName = new JTextField(20);
        JTextField txtEmail = new JTextField(20);
        JTextField txtPhone = new JTextField(20);
        JComboBox<String> cmbStatus = new JComboBox<String>(new String[]{"Outpatient", "Inpatient"});
        JTextField txtDisease = new JTextField(20);
        JTextField txtDoctor = new JTextField(20);
        JTextField txtRoom = new JTextField(20);
        JTextField txtBill = new JTextField(20);
        txtBill.setText("0.0");

        JPanel panel = new JPanel(new java.awt.GridLayout(8, 2, 5, 5));
        panel.add(new JLabel("Full Name:"));
        panel.add(txtName);
        panel.add(new JLabel("Email:"));
        panel.add(txtEmail);
        panel.add(new JLabel("Phone:"));
        panel.add(txtPhone);
        panel.add(new JLabel("Status:"));
        panel.add(cmbStatus);
        panel.add(new JLabel("Disease:"));
        panel.add(txtDisease);
        panel.add(new JLabel("Assigned Doctor:"));
        panel.add(txtDoctor);
        panel.add(new JLabel("Room (optional):"));
        panel.add(txtRoom);
        panel.add(new JLabel("Initial Bill:"));
        panel.add(txtBill);

        int result = JOptionPane.showConfirmDialog(this, panel, "Add New Patient",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            String name = txtName.getText().trim();
            String email = txtEmail.getText().trim();
            String phone = txtPhone.getText().trim();
            String status = (String) cmbStatus.getSelectedItem();
            String disease = txtDisease.getText().trim();
            String doctor = txtDoctor.getText().trim();
            String room = txtRoom.getText().trim();
            double bill = 0.0;

            // Validation
            if (name.isEmpty() || email.isEmpty() || phone.isEmpty() || doctor.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all required fields",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                bill = Double.parseDouble(txtBill.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid bill amount",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Generate Patient ID
            String patientId = "P" + String.format("%03d", dataStore.getPatients().size() + 1);

            Patient newPatient = new Patient(
                patientId, name, email, phone, status, disease,
                "Checked In", doctor, room.isEmpty() ? null : room, bill
            );

            dataStore.getPatients().add(newPatient);
            loadPatientsData();
            JOptionPane.showMessageDialog(this, "Patient added successfully!",
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddPatientActionPerformed
    private void loadAllData() {
        loadSignupData();
        loadPatientsData();
        loadReservationsData();
        loadRoomsData();
        loadBillingData();
        loadUsersData();
    }
    
    private void loadSignupData() {
        DefaultTableModel model = (DefaultTableModel) tblSignup.getModel();
        model.setRowCount(0);
        
        List<Signup> signups = dataStore.getSignup();
        for (Signup s : signups) {
            if (s.getPatientId() == null) { // Only pending signups
                model.addRow(new Object[]{
                    s.getFullName(),
                    s.getEmail(),
                    s.getPhone(),
                    s.getAddress(),
                    s.getUsername()
                });
            }
        }
    }
    
    private void loadPatientsData() {
        DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();
        model.setRowCount(0);
        
        List<Patient> patients = dataStore.getPatients();
        for (Patient p : patients) {
            model.addRow(new Object[]{
                p.getPatientId(),
                p.getFullName(),
                p.getPatientStatus(),
                p.getDisease(),
                p.getAssignedDoctor(),
                p.getAssignedRoom(),
                p.getBill()
            });
        }
    }
    
    private void loadReservationsData() {
        DefaultTableModel model = (DefaultTableModel) tblReservations.getModel();
        model.setRowCount(0);
        
        List<Reservation> reservations = dataStore.getReservations();
        for (Reservation r : reservations) {
            model.addRow(new Object[]{
                r.getReservationId(),
                r.getPatientId(),
                r.getType(),
                r.getAssignedDoctor(),
                r.getDate(),
                r.getStatus(),
                r.getNotes()
            });
        }
    }
    
    private void loadRoomsData() {
        DefaultTableModel model = (DefaultTableModel) tblRooms.getModel();
        model.setRowCount(0);
        
        List<Room> rooms = dataStore.getRooms();
        for (Room r : rooms) {
            model.addRow(new Object[]{
                r.getRoomNumber(),
                r.getPatientId(),
                r.getStatus(),
                r.getAssignedCleaner(),
                r.getCleaningStatus()
            });
        }
    }
    
    private void loadBillingData() {
        DefaultTableModel model = (DefaultTableModel) tblBilling.getModel();
        model.setRowCount(0);
        
        List<Billing> billings = dataStore.getBillings();
        for (Billing b : billings) {
            model.addRow(new Object[]{
                b.getBillingId(),
                b.getPatientId(),
                b.getDescription(),
                b.getAmount(),
                b.getStatus()
            });
        }
    }
    
    private void loadUsersData() {
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        model.setRowCount(0);
        
        List<User> users = dataStore.getUsers();
        for (User u : users) {
            model.addRow(new Object[]{
                u.getUsername(),
                u.getRole()
            });
        }
    }
    
   
    /**
     * @param args the command line arguments
     */
    /**
    public static void main(String args[]) {
       
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBilling;
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnApproveReservation;
    private javax.swing.JButton btnApproveSignup;
    private javax.swing.JButton btnDeclineReservation;
    private javax.swing.JButton btnDeletePatient;
    private javax.swing.JButton btnDeleteRoom;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnEditBilling;
    private javax.swing.JButton btnEditPatient;
    private javax.swing.JButton btnEditRoom;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMarkPaid;
    private javax.swing.JButton btnRefreshBilling;
    private javax.swing.JButton btnRefreshPatients;
    private javax.swing.JButton btnRefreshReservations;
    private javax.swing.JButton btnRefreshRooms;
    private javax.swing.JButton btnRefreshSignup;
    private javax.swing.JButton btnRefreshUsers;
    private javax.swing.JButton btnRejectSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panelBilling;
    private javax.swing.JPanel panelPatients;
    private javax.swing.JPanel panelReservations;
    private javax.swing.JPanel panelRooms;
    private javax.swing.JPanel panelSignup;
    private javax.swing.JPanel panelUsers;
    private javax.swing.JTable tblBilling;
    private javax.swing.JTable tblPatients;
    private javax.swing.JTable tblReservations;
    private javax.swing.JTable tblRooms;
    private javax.swing.JTable tblSignup;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
