/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hospital.ui;

import com.hospital.models.*;
import com.hospital.utils.DataStore;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
        
        
        
/**
 *
 * @author lenovo
 */
public class CashierDashboard extends javax.swing.JFrame {

    private String username;
    private DataStore dataStore;

    public CashierDashboard(String username) {
        this.username = username;
        this.dataStore = DataStore.getInstance();
        initComponents();
        setLocationRelativeTo(null);
        lblWelcome.setText("Welcome, " + username);
        loadAllData();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelBilling = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBilling = new javax.swing.JTable();
        btnAddBilling = new javax.swing.JButton();
        btnEditBilling = new javax.swing.JButton();
        btnMarkPaid = new javax.swing.JButton();
        btnViewBilling = new javax.swing.JButton();
        btnRefreshBilling = new javax.swing.JButton();
        btnSearchBilling = new javax.swing.JButton();
        txtSearchBilling = new javax.swing.JTextField();
        cmbFilterStatus = new javax.swing.JComboBox();
        panelSummary = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSummary = new javax.swing.JTextArea();
        btnRefreshSummary = new javax.swing.JButton();
        btnGenerateReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Cashier Dashboard");

        lblWelcome.setBackground(new java.awt.Color(255, 255, 255));
        lblWelcome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 204, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome, Cashier");

        btnLogout.setBackground(new java.awt.Color(255, 51, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jTabbedPane1.setForeground(new java.awt.Color(0, 204, 204));

        tblBilling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Bill ID", "Patient ID", "Patient Name", "Description", "Amount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBilling);

        btnAddBilling.setBackground(new java.awt.Color(0, 204, 102));
        btnAddBilling.setText("Add Billing");
        btnAddBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBillingActionPerformed(evt);
            }
        });

        btnEditBilling.setBackground(new java.awt.Color(255, 153, 0));
        btnEditBilling.setText("Edit");
        btnEditBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBillingActionPerformed(evt);
            }
        });

        btnMarkPaid.setBackground(new java.awt.Color(0, 204, 255));
        btnMarkPaid.setText("Mark Paid");
        btnMarkPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkPaidActionPerformed(evt);
            }
        });

        btnViewBilling.setBackground(new java.awt.Color(153, 153, 153));
        btnViewBilling.setText("View Details");
        btnViewBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBillingActionPerformed(evt);
            }
        });

        btnRefreshBilling.setBackground(new java.awt.Color(255, 51, 0));
        btnRefreshBilling.setText("Refresh");
        btnRefreshBilling.setPreferredSize(new java.awt.Dimension(92, 63));

        btnSearchBilling.setText("Search");
        btnSearchBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBillingActionPerformed(evt);
            }
        });

        cmbFilterStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Unpaid", "Paid" }));
        cmbFilterStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBillingLayout = new javax.swing.GroupLayout(panelBilling);
        panelBilling.setLayout(panelBillingLayout);
        panelBillingLayout.setHorizontalGroup(
            panelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillingLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSearchBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(cmbFilterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBillingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewBilling)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, Short.MAX_VALUE)
                .addComponent(btnAddBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMarkPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBillingLayout.setVerticalGroup(
            panelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchBilling)
                    .addComponent(txtSearchBilling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFilterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMarkPaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRefreshBilling, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewBilling, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAddBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Billing Management", panelBilling);

        txtSummary.setColumns(20);
        txtSummary.setRows(5);
        jScrollPane2.setViewportView(txtSummary);

        btnRefreshSummary.setBackground(new java.awt.Color(0, 204, 102));
        btnRefreshSummary.setText("Refresh Summary");

        btnGenerateReport.setBackground(new java.awt.Color(0, 204, 255));
        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSummaryLayout = new javax.swing.GroupLayout(panelSummary);
        panelSummary.setLayout(panelSummaryLayout);
        panelSummaryLayout.setHorizontalGroup(
            panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSummaryLayout.createSequentialGroup()
                .addGap(0, 714, Short.MAX_VALUE)
                .addComponent(btnGenerateReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshSummary)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        panelSummaryLayout.setVerticalGroup(
            panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshSummary)
                    .addComponent(btnGenerateReport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Payment Summary", panelSummary);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
            .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBillingActionPerformed
        JTextField txtPatientId = new JTextField(15);
        JTextField txtDescription = new JTextField(20);
        JTextField txtAmount = new JTextField(10);
        JComboBox<String> cmbStatus = new JComboBox<String>(new String[]{"Unpaid", "Paid"});

        JPanel panel = new JPanel(new java.awt.GridLayout(4, 2, 10, 10));
        panel.add(new JLabel("Patient ID:"));
        panel.add(txtPatientId);
        panel.add(new JLabel("Description:"));
        panel.add(txtDescription);
        panel.add(new JLabel("Amount:"));
        panel.add(txtAmount);
        panel.add(new JLabel("Status:"));
        panel.add(cmbStatus);

        int result = JOptionPane.showConfirmDialog(this, panel, "Add New Billing", 
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            String patientId = txtPatientId.getText().trim();
            String description = txtDescription.getText().trim();
            String status = (String) cmbStatus.getSelectedItem();

            if (patientId.isEmpty() || description.isEmpty() || txtAmount.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all fields", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double amount;
            try {
                amount = Double.parseDouble(txtAmount.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid amount", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Verify patient exists
            if (dataStore.getPatientById(patientId) == null) {
                JOptionPane.showMessageDialog(this, "Patient ID not found", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String billId = "BILL" + String.format("%03d", dataStore.getBillings().size() + 1);
            
            Billing newBilling = new Billing(billId, patientId, description, amount, status);
            dataStore.getBillings().add(newBilling);
            loadBillingData();
            loadPaymentSummary();
            JOptionPane.showMessageDialog(this, "Billing added successfully!", 
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddBillingActionPerformed

    private void btnEditBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBillingActionPerformed
        int selectedRow = tblBilling.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a billing to edit", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String billId = (String) tblBilling.getValueAt(selectedRow, 0);
        
        Billing billing = null;
        for (Billing b : dataStore.getBillings()) {
            if (b.getBillingId().equals(billId)) {
                billing = b;
                break;
            }
        }

        if (billing == null) return;

        JTextField txtDescription = new JTextField(billing.getDescription(), 20);
        JTextField txtAmount = new JTextField(String.valueOf(billing.getAmount()), 10);
        JComboBox<String> cmbStatus = new JComboBox<String>(new String[]{"Unpaid", "Paid"});
        cmbStatus.setSelectedItem(billing.getStatus());

        JPanel panel = new JPanel(new java.awt.GridLayout(3, 2, 10, 10));
        panel.add(new JLabel("Description:"));
        panel.add(txtDescription);
        panel.add(new JLabel("Amount:"));
        panel.add(txtAmount);
        panel.add(new JLabel("Status:"));
        panel.add(cmbStatus);

        int result = JOptionPane.showConfirmDialog(this, panel, "Edit Billing: " + billId, 
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            try {
                billing.setDescription(txtDescription.getText().trim());
                billing.setAmount(Double.parseDouble(txtAmount.getText().trim()));
                billing.setStatus((String) cmbStatus.getSelectedItem());

                loadBillingData();
                loadPaymentSummary();
                JOptionPane.showMessageDialog(this, "Billing updated successfully!", 
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error updating billing: " + e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditBillingActionPerformed

    private void btnMarkPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkPaidActionPerformed
        int selectedRow = tblBilling.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a billing to mark as paid", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String billId = (String) tblBilling.getValueAt(selectedRow, 0);
        String currentStatus = (String) tblBilling.getValueAt(selectedRow, 5);

        if (currentStatus.equals("Paid")) {
            JOptionPane.showMessageDialog(this, "This bill is already paid", 
                "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, 
            "Mark billing " + billId + " as paid?", 
            "Confirm Payment", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            for (Billing b : dataStore.getBillings()) {
                if (b.getBillingId().equals(billId)) {
                    b.setStatus("Paid");
                    break;
                }
            }

            loadBillingData();
            loadPaymentSummary();
            JOptionPane.showMessageDialog(this, "Billing marked as paid", 
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnMarkPaidActionPerformed

    private void btnViewBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBillingActionPerformed
        int selectedRow = tblBilling.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a billing to view", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String billId = (String) tblBilling.getValueAt(selectedRow, 0);
        
        Billing billing = null;
        for (Billing b : dataStore.getBillings()) {
            if (b.getBillingId().equals(billId)) {
                billing = b;
                break;
            }
        }

        if (billing == null) return;

        Patient patient = dataStore.getPatientById(billing.getPatientId());

        StringBuilder details = new StringBuilder();
        details.append("BILLING DETAILS\n");
        details.append("═══════════════════════════════════\n\n");
        details.append("Billing ID: ").append(billing.getBillingId()).append("\n");
        details.append("Patient ID: ").append(billing.getPatientId()).append("\n");
        if (patient != null) {
            details.append("Patient Name: ").append(patient.getFullName()).append("\n");
            details.append("Patient Phone: ").append(patient.getPhone()).append("\n");
        }
        details.append("\nDescription: ").append(billing.getDescription()).append("\n");
        details.append("Amount: Php").append(String.format("%.2f", billing.getAmount())).append("\n");
        details.append("Status: ").append(billing.getStatus()).append("\n");

        JTextArea textArea = new JTextArea(details.toString());
        textArea.setEditable(false);
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(400, 250));

        JOptionPane.showMessageDialog(this, scrollPane, "Billing Details", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewBillingActionPerformed

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
         String reportContent = txtSummary.getText();
        
        try {
            String filename = "payment_report_" + 
                new java.text.SimpleDateFormat("yyyyMMdd_HHmmss").format(new java.util.Date()) + ".txt";
            java.io.FileWriter writer = new java.io.FileWriter(filename);
            writer.write(reportContent);
            writer.close();
            
            JOptionPane.showMessageDialog(this, 
                "Report saved to: " + filename, 
                "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error saving report: " + e.getMessage(), 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to logout?", 
            "Confirm Logout", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void cmbFilterStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterStatusActionPerformed
       filterBilling();
    }//GEN-LAST:event_cmbFilterStatusActionPerformed

    private void btnSearchBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBillingActionPerformed
        searchBilling();
    }//GEN-LAST:event_btnSearchBillingActionPerformed
    private void loadAllData() {
        loadBillingData();
        loadPaymentSummary();
    }
    
    private void loadBillingData() {
        DefaultTableModel model = (DefaultTableModel) tblBilling.getModel();
        model.setRowCount(0);

        List<Billing> billings = dataStore.getBillings();
        for (Billing b : billings) {
            Patient patient = dataStore.getPatientById(b.getPatientId());
            String patientName = patient != null ? patient.getFullName() : "Unknown";
            
            model.addRow(new Object[]{
                b.getBillingId(),
                b.getPatientId(),
                patientName,
                b.getDescription(),
                String.format("Php%.2f", b.getAmount()),
                b.getStatus()
            });
        }
    }
    
    private void searchBilling() {
        String searchText = txtSearchBilling.getText().trim().toLowerCase();
        
        DefaultTableModel model = (DefaultTableModel) tblBilling.getModel();
        model.setRowCount(0);

        List<Billing> billings = dataStore.getBillings();
        for (Billing b : billings) {
            if (searchText.isEmpty() ||
                b.getBillingId().toLowerCase().contains(searchText) ||
                b.getPatientId().toLowerCase().contains(searchText) ||
                b.getDescription().toLowerCase().contains(searchText)) {
                
                Patient patient = dataStore.getPatientById(b.getPatientId());
                String patientName = patient != null ? patient.getFullName() : "Unknown";
                
                model.addRow(new Object[]{
                    b.getBillingId(),
                    b.getPatientId(),
                    patientName,
                    b.getDescription(),
                    String.format("Php%.2f", b.getAmount()),
                    b.getStatus()
                });
            }
        }
    }
    
    private void filterBilling() {
        String filter = (String) cmbFilterStatus.getSelectedItem();
        
        DefaultTableModel model = (DefaultTableModel) tblBilling.getModel();
        model.setRowCount(0);

        List<Billing> billings = dataStore.getBillings();
        for (Billing b : billings) {
            if (filter.equals("All") || b.getStatus().equals(filter)) {
                Patient patient = dataStore.getPatientById(b.getPatientId());
                String patientName = patient != null ? patient.getFullName() : "Unknown";
                
                model.addRow(new Object[]{
                    b.getBillingId(),
                    b.getPatientId(),
                    patientName,
                    b.getDescription(),
                    String.format("Php%.2f", b.getAmount()),
                    b.getStatus()
                });
            }
        }
    }
    
    private void loadPaymentSummary() {
        StringBuilder summary = new StringBuilder();
        summary.append("PAYMENT SUMMARY REPORT\n");
        summary.append("═══════════════════════════════════════\n");
        summary.append("Generated: ").append(new java.util.Date().toString()).append("\n\n");

        List<Billing> billings = dataStore.getBillings();
        
        double totalRevenue = 0.0;
        double paidAmount = 0.0;
        double unpaidAmount = 0.0;
        int totalBills = billings.size();
        int paidBills = 0;
        int unpaidBills = 0;

        for (Billing b : billings) {
            totalRevenue += b.getAmount();
            if (b.getStatus().equals("Paid")) {
                paidAmount += b.getAmount();
                paidBills++;
            } else {
                unpaidAmount += b.getAmount();
                unpaidBills++;
            }
        }

        summary.append("FINANCIAL OVERVIEW:\n");
        summary.append("───────────────────────────────────────\n");
        summary.append("Total Bills: ").append(totalBills).append("\n");
        summary.append("Total Revenue: Php").append(String.format("%.2f", totalRevenue)).append("\n\n");
        
        summary.append("PAID:\n");
        summary.append("  Count: ").append(paidBills).append("\n");
        summary.append("  Amount: Php").append(String.format("%.2f", paidAmount)).append("\n\n");
        
        summary.append("UNPAID:\n");
        summary.append("  Count: ").append(unpaidBills).append("\n");
        summary.append("  Amount: Php").append(String.format("%.2f", unpaidAmount)).append("\n\n");
        
        double paymentRate = totalRevenue > 0 ? (paidAmount / totalRevenue) * 100 : 0;
        summary.append("Payment Collection Rate: ").append(String.format("%.1f", paymentRate)).append("%\n\n");
        
        summary.append("TODAY'S TRANSACTIONS:\n");
        summary.append("───────────────────────────────────────\n");
        summary.append("(Real-time tracking would be implemented here)\n");

        txtSummary.setText(summary.toString());
        txtSummary.setCaretPosition(0);
    }
    
    
    /**
     * @param args the command line arguments
     */
    /**public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierDashboard().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBilling;
    private javax.swing.JButton btnEditBilling;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMarkPaid;
    private javax.swing.JButton btnRefreshBilling;
    private javax.swing.JButton btnRefreshSummary;
    private javax.swing.JButton btnSearchBilling;
    private javax.swing.JButton btnViewBilling;
    private javax.swing.JComboBox cmbFilterStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panelBilling;
    private javax.swing.JPanel panelSummary;
    private javax.swing.JTable tblBilling;
    private javax.swing.JTextField txtSearchBilling;
    private javax.swing.JTextArea txtSummary;
    // End of variables declaration//GEN-END:variables
}
