/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hospital.ui;


import com.hospital.models.*;
import com.hospital.utils.DataStore;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;


/**
 *
 * @author lenovo
 */
public class CoAdminDashboard extends javax.swing.JFrame {

    private String username;
    private DataStore dataStore;

    public CoAdminDashboard(String username) {
        this.username = username;
        this.dataStore = DataStore.getInstance();
        initComponents();
        setLocationRelativeTo(null);
        lblWelcome.setText("Welcome, " + username);
        loadAllData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelSignup = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSignup = new javax.swing.JTable();
        btnApproveSignup = new javax.swing.JButton();
        btnRejectSignup = new javax.swing.JButton();
        btnRefreshSignup = new javax.swing.JButton();
        panelPatients = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPatients = new javax.swing.JTable();
        btnViewPatient = new javax.swing.JButton();
        btnRefreshPatients = new javax.swing.JButton();
        btnSearchPatients = new javax.swing.JButton();
        txtSearchPatients = new javax.swing.JTextField();
        panelReservations = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblReservations = new javax.swing.JTable();
        btnApproveReservation = new javax.swing.JButton();
        btnDeclineReservation = new javax.swing.JButton();
        btnRefreshReservations = new javax.swing.JButton();
        panelRooms = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRooms = new javax.swing.JTable();
        btnRefreshRooms = new javax.swing.JButton();
        panelBilling = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblBilling = new javax.swing.JTable();
        btnRefreshBilling = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Co-Admin Dashboard");

        lblWelcome.setBackground(new java.awt.Color(255, 255, 255));
        lblWelcome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 204, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome, Co-Admin");

        btnLogout.setBackground(new java.awt.Color(255, 51, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jTabbedPane1.setForeground(new java.awt.Color(0, 204, 204));

        tblSignup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Email", "Phone", "Address", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSignup);

        btnApproveSignup.setText("Approve");
        btnApproveSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveSignupActionPerformed(evt);
            }
        });

        btnRejectSignup.setText("Reject");
        btnRejectSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectSignupActionPerformed(evt);
            }
        });

        btnRefreshSignup.setText("Refresh");
        btnRefreshSignup.setPreferredSize(new java.awt.Dimension(92, 63));

        javax.swing.GroupLayout panelSignupLayout = new javax.swing.GroupLayout(panelSignup);
        panelSignup.setLayout(panelSignupLayout);
        panelSignupLayout.setHorizontalGroup(
            panelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSignupLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnApproveSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnRejectSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSignupLayout.setVerticalGroup(
            panelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignupLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApproveSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRejectSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        jTabbedPane1.addTab("Signup Requests", panelSignup);

        tblPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Status", "Disease", "Doctor", "Room", "Bill"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPatients);

        btnViewPatient.setBackground(new java.awt.Color(153, 153, 153));
        btnViewPatient.setText("View Details");
        btnViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientActionPerformed(evt);
            }
        });

        btnRefreshPatients.setBackground(new java.awt.Color(0, 204, 102));
        btnRefreshPatients.setText("Refresh");
        btnRefreshPatients.setPreferredSize(new java.awt.Dimension(92, 63));

        btnSearchPatients.setText("Search");
        btnSearchPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPatientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPatientsLayout = new javax.swing.GroupLayout(panelPatients);
        panelPatients.setLayout(panelPatientsLayout);
        panelPatientsLayout.setHorizontalGroup(
            panelPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPatientsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPatientsLayout.createSequentialGroup()
                        .addComponent(txtSearchPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchPatients))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPatientsLayout.createSequentialGroup()
                        .addComponent(btnViewPatient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefreshPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelPatientsLayout.setVerticalGroup(
            panelPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPatientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchPatients)
                    .addComponent(txtSearchPatients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRefreshPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Patients", panelPatients);

        tblReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Patient ID", "Type", "Doctor", "Date", "Status", "Notes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblReservations);

        btnApproveReservation.setBackground(new java.awt.Color(0, 204, 102));
        btnApproveReservation.setText("Approve");
        btnApproveReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveReservationActionPerformed(evt);
            }
        });

        btnDeclineReservation.setBackground(new java.awt.Color(255, 51, 0));
        btnDeclineReservation.setText("Decline");
        btnDeclineReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineReservationActionPerformed(evt);
            }
        });

        btnRefreshReservations.setBackground(new java.awt.Color(0, 204, 102));
        btnRefreshReservations.setText("Refresh");
        btnRefreshReservations.setPreferredSize(new java.awt.Dimension(92, 63));

        javax.swing.GroupLayout panelReservationsLayout = new javax.swing.GroupLayout(panelReservations);
        panelReservations.setLayout(panelReservationsLayout);
        panelReservationsLayout.setHorizontalGroup(
            panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservationsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApproveReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeclineReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelReservationsLayout.setVerticalGroup(
            panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservationsLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeclineReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApproveReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(223, 223, 223))
        );

        jTabbedPane1.addTab("Reservations", panelReservations);

        tblRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room No", "Patient ID", "Status", "Cleaner", "Cleaning Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblRooms);

        btnRefreshRooms.setBackground(new java.awt.Color(0, 204, 102));
        btnRefreshRooms.setText("Refresh");

        javax.swing.GroupLayout panelRoomsLayout = new javax.swing.GroupLayout(panelRooms);
        panelRooms.setLayout(panelRoomsLayout);
        panelRoomsLayout.setHorizontalGroup(
            panelRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoomsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefreshRooms)
                .addContainerGap())
            .addGroup(panelRoomsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE))
        );
        panelRoomsLayout.setVerticalGroup(
            panelRoomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoomsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefreshRooms)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rooms", panelRooms);

        tblBilling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Bill ID", "Patient ID", "Description", "Amount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblBilling);

        btnRefreshBilling.setBackground(new java.awt.Color(0, 204, 102));
        btnRefreshBilling.setText("Refresh");

        javax.swing.GroupLayout panelBillingLayout = new javax.swing.GroupLayout(panelBilling);
        panelBilling.setLayout(panelBillingLayout);
        panelBillingLayout.setHorizontalGroup(
            panelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBillingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefreshBilling)
                .addContainerGap())
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
        );
        panelBillingLayout.setVerticalGroup(
            panelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefreshBilling)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Billing (History Only)", panelBilling);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
            .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveSignupActionPerformed
       int selectedRow = tblSignup.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a signup request", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String username = (String) tblSignup.getValueAt(selectedRow, 4);
        
        Signup signup = null;
        for (Signup s : dataStore.getSignup()) {
            if (s.getUsername().equals(username) && s.getPatientId() == null) {
                signup = s;
                break;
            }
        }

        if (signup == null) return;

        String[] statusOptions = {"Outpatient", "Inpatient"};
        String patientStatus = (String) JOptionPane.showInputDialog(this, 
            "Select Patient Status:", "Approve Signup",
            JOptionPane.QUESTION_MESSAGE, null, statusOptions, statusOptions[0]);
        
        if (patientStatus == null) return;

        String doctor = JOptionPane.showInputDialog(this, "Assign Doctor (username):", "dr.juan");
        if (doctor == null) return;

        String room = null;
        if (patientStatus.equals("Inpatient")) {
            room = JOptionPane.showInputDialog(this, "Assign Room:", "R101");
        }

        String patientId = "P" + String.format("%03d", dataStore.getPatients().size() + 1);
        
        signup.setPatientId(patientId);
        signup.setPatientStatus(patientStatus);
        signup.setAssignedDoctor(doctor);
        signup.setAssignedRoom(room);

        Patient newPatient = new Patient(
            patientId,
            signup.getFullName(),
            signup.getEmail(),
            signup.getPhone(),
            patientStatus,
            "Not Diagnosed",
            "Checked In",
            doctor,
            room,
            0.0
        );
        dataStore.getPatients().add(newPatient);

        JOptionPane.showMessageDialog(this, "Signup approved!", "Success", JOptionPane.INFORMATION_MESSAGE);
        loadSignupData();
        loadPatientsData();
    }//GEN-LAST:event_btnApproveSignupActionPerformed

    private void btnRejectSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectSignupActionPerformed
        int selectedRow = tblSignup.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a signup request", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to reject this signup?", 
            "Confirm", JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) return;

        String username = (String) tblSignup.getValueAt(selectedRow, 4);
        
        Signup toRemove = null;
        for (Signup s : dataStore.getSignup()) {
            if (s.getUsername().equals(username) && s.getPatientId() == null) {
                toRemove = s;
                break;
            }
        }

        if (toRemove != null) {
            dataStore.getSignup().remove(toRemove);
            JOptionPane.showMessageDialog(this, "Signup rejected", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadSignupData();
        }
    }//GEN-LAST:event_btnRejectSignupActionPerformed

    private void btnViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientActionPerformed
        int selectedRow = tblPatients.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a patient", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String patientId = (String) tblPatients.getValueAt(selectedRow, 0);
        Patient patient = dataStore.getPatientById(patientId);

        if (patient == null) return;

        StringBuilder details = new StringBuilder();
        details.append("PATIENT DETAILS\n");
        details.append("═══════════════════════════════════\n\n");
        details.append("Patient ID: ").append(patient.getPatientId()).append("\n");
        details.append("Name: ").append(patient.getFullName()).append("\n");
        details.append("Email: ").append(patient.getEmail()).append("\n");
        details.append("Phone: ").append(patient.getPhone()).append("\n\n");
        details.append("Type: ").append(patient.getPatientStatus()).append("\n");
        details.append("Disease: ").append(patient.getDisease()).append("\n");
        details.append("Status: ").append(patient.getStatus()).append("\n");
        details.append("Doctor: ").append(patient.getAssignedDoctor()).append("\n");
        details.append("Room: ").append(patient.getAssignedRoom() != null ? patient.getAssignedRoom() : "N/A").append("\n");
        details.append("Bill: Php").append(String.format("%.2f", patient.getBill())).append("\n");

        JTextArea textArea = new JTextArea(details.toString());
        textArea.setEditable(false);
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(400, 300));

        JOptionPane.showMessageDialog(this, scrollPane, "Patient Details", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewPatientActionPerformed

    private void btnApproveReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveReservationActionPerformed
        int selectedRow = tblReservations.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a reservation", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String resId = (String) tblReservations.getValueAt(selectedRow, 0);
        
        for (Reservation r : dataStore.getReservations()) {
            if (r.getReservationId().equals(resId)) {
                r.setStatus("Approved");
                String notes = JOptionPane.showInputDialog(this, "Add notes (optional):", "");
                if (notes != null) {
                    r.setNotes(notes);
                }
                break;
            }
        }

        loadReservationsData();
        JOptionPane.showMessageDialog(this, "Reservation approved", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnApproveReservationActionPerformed

    private void btnDeclineReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineReservationActionPerformed
        int selectedRow = tblReservations.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a reservation", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String resId = (String) tblReservations.getValueAt(selectedRow, 0);
        String reason = JOptionPane.showInputDialog(this, "Reason for declining:", "");
        
        if (reason != null) {
            for (Reservation r : dataStore.getReservations()) {
                if (r.getReservationId().equals(resId)) {
                    r.setStatus("Declined");
                    r.setNotes(reason);
                    break;
                }
            }

            loadReservationsData();
            JOptionPane.showMessageDialog(this, "Reservation declined", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeclineReservationActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to logout?", 
            "Confirm Logout", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSearchPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPatientsActionPerformed
        searchPatients();
    }//GEN-LAST:event_btnSearchPatientsActionPerformed
    private void loadAllData() {
        loadSignupData();
        loadPatientsData();
        loadReservationsData();
        loadRoomsData();
        loadBillingData();
    }
    
    private void loadSignupData() {
        DefaultTableModel model = (DefaultTableModel) tblSignup.getModel();
        model.setRowCount(0);
        
        List<Signup> signups = dataStore.getSignup();
        for (Signup s : signups) {
            if (s.getPatientId() == null) {
                model.addRow(new Object[]{
                    s.getFullName(),
                    s.getEmail(),
                    s.getPhone(),
                    s.getAddress(),
                    s.getUsername()
                });
            }
        }
    }
    
    private void loadPatientsData() {
        DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();
        model.setRowCount(0);
        
        List<Patient> patients = dataStore.getPatients();
        for (Patient p : patients) {
            model.addRow(new Object[]{
                p.getPatientId(),
                p.getFullName(),
                p.getPatientStatus(),
                p.getDisease(),
                p.getAssignedDoctor(),
                p.getAssignedRoom(),
                p.getBill()
            });
        }
    }
    
    private void searchPatients() {
        String searchText = txtSearchPatients.getText().trim().toLowerCase();
        
        DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();
        model.setRowCount(0);

        List<Patient> patients = dataStore.getPatients();
        for (Patient p : patients) {
            if (searchText.isEmpty() ||
                p.getPatientId().toLowerCase().contains(searchText) ||
                p.getFullName().toLowerCase().contains(searchText)) {
                
                model.addRow(new Object[]{
                    p.getPatientId(),
                    p.getFullName(),
                    p.getPatientStatus(),
                    p.getDisease(),
                    p.getAssignedDoctor(),
                    p.getAssignedRoom(),
                    p.getBill()
                });
            }
        }
    }
    
    private void loadReservationsData() {
        DefaultTableModel model = (DefaultTableModel) tblReservations.getModel();
        model.setRowCount(0);
        
        List<Reservation> reservations = dataStore.getReservations();
        for (Reservation r : reservations) {
            model.addRow(new Object[]{
                r.getReservationId(),
                r.getPatientId(),
                r.getType(),
                r.getAssignedDoctor(),
                r.getDate(),
                r.getStatus(),
                r.getNotes()
            });
        }
    }
    
    private void loadRoomsData() {
        DefaultTableModel model = (DefaultTableModel) tblRooms.getModel();
        model.setRowCount(0);
        
        List<Room> rooms = dataStore.getRooms();
        for (Room r : rooms) {
            model.addRow(new Object[]{
                r.getRoomNumber(),
                r.getPatientId(),
                r.getStatus(),
                r.getAssignedCleaner(),
                r.getCleaningStatus()
            });
        }
    }
    
    private void loadBillingData() {
        DefaultTableModel model = (DefaultTableModel) tblBilling.getModel();
        model.setRowCount(0);
        
        List<Billing> billings = dataStore.getBillings();
        for (Billing b : billings) {
            model.addRow(new Object[]{
                b.getBillingId(),
                b.getPatientId(),
                b.getDescription(),
                b.getAmount(),
                b.getStatus()
            });
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    /**public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoAdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoAdminDashboard().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveReservation;
    private javax.swing.JButton btnApproveSignup;
    private javax.swing.JButton btnDeclineReservation;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefreshBilling;
    private javax.swing.JButton btnRefreshPatients;
    private javax.swing.JButton btnRefreshReservations;
    private javax.swing.JButton btnRefreshRooms;
    private javax.swing.JButton btnRefreshSignup;
    private javax.swing.JButton btnRejectSignup;
    private javax.swing.JButton btnSearchPatients;
    private javax.swing.JButton btnViewPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panelBilling;
    private javax.swing.JPanel panelPatients;
    private javax.swing.JPanel panelReservations;
    private javax.swing.JPanel panelRooms;
    private javax.swing.JPanel panelSignup;
    private javax.swing.JTable tblBilling;
    private javax.swing.JTable tblPatients;
    private javax.swing.JTable tblReservations;
    private javax.swing.JTable tblRooms;
    private javax.swing.JTable tblSignup;
    private javax.swing.JTextField txtSearchPatients;
    // End of variables declaration//GEN-END:variables
}
