/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hospital.ui;

import com.hospital.models.*;
import com.hospital.utils.DataStore;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;



/**
 *
 * @author lenovo
 */
public class DoctorDashboard extends javax.swing.JFrame {

    private String username;
    private DataStore dataStore;

    public DoctorDashboard(String username) {
        this.username = username;
        this.dataStore = DataStore.getInstance();
        initComponents();
        setLocationRelativeTo(null);
        lblWelcome.setText("Welcome, Dr. " + username);
        loadAllData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelMyPatients = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatients = new javax.swing.JTable();
        btnViewPatient = new javax.swing.JButton();
        btnUpdateStatus = new javax.swing.JButton();
        btnSearchPatient = new javax.swing.JButton();
        txtSearchPatient = new javax.swing.JTextField();
        btnRefreshPatients = new javax.swing.JButton();
        btnUpdateDiagnosis = new javax.swing.JButton();
        panelSchedule = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        btnRefreshSchedule = new javax.swing.JButton();
        panelReservations = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReservations = new javax.swing.JTable();
        btnViewReservation = new javax.swing.JButton();
        btnRefreshReservations = new javax.swing.JButton();
        cmbFilterReservations = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Doctor Dashboard");

        lblWelcome.setBackground(new java.awt.Color(255, 255, 255));
        lblWelcome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 204, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome, Doctor");

        btnLogout.setBackground(new java.awt.Color(255, 51, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jTabbedPane1.setForeground(new java.awt.Color(0, 204, 204));

        tblPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Type", "Disease", "Status", "Room", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPatients);

        btnViewPatient.setBackground(new java.awt.Color(153, 153, 153));
        btnViewPatient.setText("View Details");
        btnViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientActionPerformed(evt);
            }
        });

        btnUpdateStatus.setBackground(new java.awt.Color(0, 204, 255));
        btnUpdateStatus.setText("Update Status");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        btnSearchPatient.setBackground(new java.awt.Color(255, 153, 0));
        btnSearchPatient.setText("Search");
        btnSearchPatient.setPreferredSize(new java.awt.Dimension(71, 25));
        btnSearchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPatientActionPerformed(evt);
            }
        });

        btnRefreshPatients.setBackground(new java.awt.Color(0, 204, 102));
        btnRefreshPatients.setText("Refresh");
        btnRefreshPatients.setPreferredSize(new java.awt.Dimension(92, 63));

        btnUpdateDiagnosis.setBackground(new java.awt.Color(255, 153, 0));
        btnUpdateDiagnosis.setText("Update Diagnosis");
        btnUpdateDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDiagnosisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMyPatientsLayout = new javax.swing.GroupLayout(panelMyPatients);
        panelMyPatients.setLayout(panelMyPatientsLayout);
        panelMyPatientsLayout.setHorizontalGroup(
            panelMyPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMyPatientsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMyPatientsLayout.createSequentialGroup()
                .addContainerGap(433, Short.MAX_VALUE)
                .addComponent(btnViewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateDiagnosis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefreshPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMyPatientsLayout.setVerticalGroup(
            panelMyPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMyPatientsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelMyPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMyPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshPatients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(436, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Patients", panelMyPatients);

        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Time", "Patient", "Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblSchedule);

        btnRefreshSchedule.setBackground(new java.awt.Color(0, 204, 102));
        btnRefreshSchedule.setText("Refresh");

        javax.swing.GroupLayout panelScheduleLayout = new javax.swing.GroupLayout(panelSchedule);
        panelSchedule.setLayout(panelScheduleLayout);
        panelScheduleLayout.setHorizontalGroup(
            panelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
            .addGroup(panelScheduleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRefreshSchedule))
        );
        panelScheduleLayout.setVerticalGroup(
            panelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScheduleLayout.createSequentialGroup()
                .addComponent(btnRefreshSchedule)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(496, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Schedule", panelSchedule);

        tblReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Patient ID", "Patient Name", "Type", "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblReservations);

        btnViewReservation.setBackground(new java.awt.Color(153, 153, 153));
        btnViewReservation.setText("View Details");
        btnViewReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReservationActionPerformed(evt);
            }
        });

        btnRefreshReservations.setBackground(new java.awt.Color(0, 204, 102));
        btnRefreshReservations.setText("Refresh");
        btnRefreshReservations.setPreferredSize(new java.awt.Dimension(92, 63));

        cmbFilterReservations.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Pending", "Approved", "Today", "This Week" }));
        cmbFilterReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterReservationsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReservationsLayout = new javax.swing.GroupLayout(panelReservations);
        panelReservations.setLayout(panelReservationsLayout);
        panelReservationsLayout.setHorizontalGroup(
            panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservationsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbFilterReservations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservationsLayout.createSequentialGroup()
                        .addComponent(btnViewReservation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefreshReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelReservationsLayout.setVerticalGroup(
            panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbFilterReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(495, 495, 495))
        );

        jTabbedPane1.addTab("My Reservations", panelReservations);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSearchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPatientActionPerformed
        searchPatients();
    }//GEN-LAST:event_btnSearchPatientActionPerformed

    private void btnViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientActionPerformed
        int selectedRow = tblPatients.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a patient", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String patientId = (String) tblPatients.getValueAt(selectedRow, 0);
        Patient patient = dataStore.getPatientById(patientId);

        if (patient == null) return;

        StringBuilder details = new StringBuilder();
        details.append("PATIENT DETAILS\n");
        details.append("═══════════════════════════════════\n\n");
        details.append("Patient ID: ").append(patient.getPatientId()).append("\n");
        details.append("Name: ").append(patient.getFullName()).append("\n");
        details.append("Email: ").append(patient.getEmail()).append("\n");
        details.append("Phone: ").append(patient.getPhone()).append("\n\n");
        details.append("Type: ").append(patient.getPatientStatus()).append("\n");
        details.append("Disease/Diagnosis: ").append(patient.getDisease()).append("\n");
        details.append("Status: ").append(patient.getStatus()).append("\n");
        details.append("Room: ").append(patient.getAssignedRoom() != null ? patient.getAssignedRoom() : "N/A").append("\n");
        details.append("Bill: Php").append(String.format("%.2f", patient.getBill())).append("\n");

        JTextArea textArea = new JTextArea(details.toString());
        textArea.setEditable(false);
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(400, 300));

        JOptionPane.showMessageDialog(this, scrollPane, "Patient Details", JOptionPane.INFORMATION_MESSAGE);
    }

    private void btnUpdateDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = tblPatients.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a patient", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String patientId = (String) tblPatients.getValueAt(selectedRow, 0);
        Patient patient = dataStore.getPatientById(patientId);

        if (patient == null) return;

        JTextArea txtDiagnosis = new JTextArea(patient.getDisease(), 5, 30);
        txtDiagnosis.setLineWrap(true);
        txtDiagnosis.setWrapStyleWord(true);
        JScrollPane scrollPane = new JScrollPane(txtDiagnosis);

        int result = JOptionPane.showConfirmDialog(this, scrollPane, 
            "Update Diagnosis for " + patient.getFullName(), 
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            String newDiagnosis = txtDiagnosis.getText().trim();
            if (!newDiagnosis.isEmpty()) {
                patient.setDisease(newDiagnosis);
                loadMyPatients();
                JOptionPane.showMessageDialog(this, "Diagnosis updated successfully", 
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnViewPatientActionPerformed

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        int selectedRow = tblPatients.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a patient", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String patientId = (String) tblPatients.getValueAt(selectedRow, 0);
        Patient patient = dataStore.getPatientById(patientId);

        if (patient == null) return;

        String[] statusOptions = {"Checked In", "Under Treatment", "Discharged", "Critical"};
        String newStatus = (String) JOptionPane.showInputDialog(this,
            "Update status for " + patient.getFullName() + ":",
            "Update Patient Status",
            JOptionPane.QUESTION_MESSAGE,
            null,
            statusOptions,
            patient.getStatus());

        if (newStatus != null) {
            patient.setStatus(newStatus);
            loadMyPatients();
            JOptionPane.showMessageDialog(this, "Status updated successfully", 
                "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void btnViewReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReservationActionPerformed
        int selectedRow = tblReservations.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a reservation", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String resId = (String) tblReservations.getValueAt(selectedRow, 0);
        Reservation reservation = null;
        for (Reservation r : dataStore.getReservations()) {
            if (r.getReservationId().equals(resId)) {
                reservation = r;
                break;
            }
        }

        if (reservation == null) return;

        Patient patient = dataStore.getPatientById(reservation.getPatientId());

        StringBuilder details = new StringBuilder();
        details.append("RESERVATION DETAILS\n");
        details.append("═══════════════════════════════════\n\n");
        details.append("Reservation ID: ").append(reservation.getReservationId()).append("\n");
        details.append("Patient: ").append(patient != null ? patient.getFullName() : "Unknown").append("\n");
        details.append("Patient ID: ").append(reservation.getPatientId()).append("\n");
        if (patient != null) {
            details.append("Phone: ").append(patient.getPhone()).append("\n");
        }
        details.append("\nType: ").append(reservation.getType()).append("\n");
        details.append("Date & Time: ").append(reservation.getDate()).append("\n");
        details.append("Status: ").append(reservation.getStatus()).append("\n");
        details.append("Notes: ").append(reservation.getNotes()).append("\n");

        JTextArea textArea = new JTextArea(details.toString());
        textArea.setEditable(false);
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(400, 300));

        JOptionPane.showMessageDialog(this, scrollPane, "Reservation Details", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewReservationActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to logout?", 
            "Confirm Logout", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed
/**
    private void btnUpdateDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDiagnosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateDiagnosisActionPerformed
*/
    private void cmbFilterReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterReservationsActionPerformed
        filterReservations();
    }//GEN-LAST:event_cmbFilterReservationsActionPerformed
    
    private void loadAllData() {
        loadMyPatients();
        loadMyReservations();
        loadSchedule();
    }
    
    private void loadMyPatients() {
        DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();
        model.setRowCount(0);

        List<Patient> patients = dataStore.getPatients();
        for (Patient p : patients) {
            if (p.getAssignedDoctor().equals(username)) {
                model.addRow(new Object[]{
                    p.getPatientId(),
                    p.getFullName(),
                    p.getPatientStatus(),
                    p.getDisease(),
                    p.getStatus(),
                    p.getAssignedRoom() != null ? p.getAssignedRoom() : "N/A",
                    p.getPhone()
                });
            }
        }
    }
    
    private void searchPatients() {
        String searchText = txtSearchPatient.getText().trim().toLowerCase();
        
        DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();
        model.setRowCount(0);

        List<Patient> patients = dataStore.getPatients();
        for (Patient p : patients) {
            if (p.getAssignedDoctor().equals(username)) {
                if (searchText.isEmpty() ||
                    p.getPatientId().toLowerCase().contains(searchText) ||
                    p.getFullName().toLowerCase().contains(searchText) ||
                    p.getDisease().toLowerCase().contains(searchText)) {
                    
                    model.addRow(new Object[]{
                        p.getPatientId(),
                        p.getFullName(),
                        p.getPatientStatus(),
                        p.getDisease(),
                        p.getStatus(),
                        p.getAssignedRoom() != null ? p.getAssignedRoom() : "N/A",
                        p.getPhone()
                    });
                }
            }
        }
    }
    
    private void loadMyReservations() {
        DefaultTableModel model = (DefaultTableModel) tblReservations.getModel();
        model.setRowCount(0);

        List<Reservation> reservations = dataStore.getReservations();
        for (Reservation r : reservations) {
            if (r.getAssignedDoctor().equals(username)) {
                Patient patient = dataStore.getPatientById(r.getPatientId());
                String patientName = patient != null ? patient.getFullName() : "Unknown";
                
                model.addRow(new Object[]{
                    r.getReservationId(),
                    r.getPatientId(),
                    patientName,
                    r.getType(),
                    r.getDate(),
                    r.getStatus()
                });
            }
        }
    }
    
    private void filterReservations() {
        String filter = (String) cmbFilterReservations.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) tblReservations.getModel();
        model.setRowCount(0);

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String today = sdf.format(new java.util.Date());
        
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.add(java.util.Calendar.DAY_OF_YEAR, 7);
        String nextWeek = sdf.format(cal.getTime());

        List<Reservation> reservations = dataStore.getReservations();
        for (Reservation r : reservations) {
            if (!r.getAssignedDoctor().equals(username)) continue;
            
            boolean include = false;
            if (filter.equals("All")) {
                include = true;
            } else if (filter.equals("Pending") && r.getStatus().equals("Pending")) {
                include = true;
            } else if (filter.equals("Approved") && r.getStatus().equals("Approved")) {
                include = true;
            } else if (filter.equals("Today") && r.getDate().startsWith(today)) {
                include = true;
            } else if (filter.equals("This Week") && 
                      r.getDate().compareTo(today) >= 0 && 
                      r.getDate().compareTo(nextWeek) <= 0) {
                include = true;
            }
            
            if (include) {
                Patient patient = dataStore.getPatientById(r.getPatientId());
                String patientName = patient != null ? patient.getFullName() : "Unknown";
                
                model.addRow(new Object[]{
                    r.getReservationId(),
                    r.getPatientId(),
                    patientName,
                    r.getType(),
                    r.getDate(),
                    r.getStatus()
                });
            }
        }
    }
    
    private void loadSchedule() {
        DefaultTableModel model = (DefaultTableModel) tblSchedule.getModel();
        model.setRowCount(0);

        List<Reservation> reservations = dataStore.getReservations();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String today = sdf.format(new java.util.Date());

        for (Reservation r : reservations) {
            if (r.getAssignedDoctor().equals(username) && 
                r.getDate().compareTo(today) >= 0 &&
                !r.getStatus().equals("Declined") &&
                !r.getStatus().equals("Cancelled")) {
                
                Patient patient = dataStore.getPatientById(r.getPatientId());
                String patientName = patient != null ? patient.getFullName() : "Unknown";
                
                String date = r.getDate().substring(0, 10);
                String time = r.getDate().length() > 10 ? r.getDate().substring(11) : "N/A";
                
                model.addRow(new Object[]{
                    date,
                    time,
                    patientName,
                    r.getType(),
                    r.getStatus()
                });
            }
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    /**public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorDashboard().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefreshPatients;
    private javax.swing.JButton btnRefreshReservations;
    private javax.swing.JButton btnRefreshSchedule;
    private javax.swing.JButton btnSearchPatient;
    private javax.swing.JButton btnUpdateDiagnosis;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JButton btnViewPatient;
    private javax.swing.JButton btnViewReservation;
    private javax.swing.JComboBox cmbFilterReservations;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panelMyPatients;
    private javax.swing.JPanel panelReservations;
    private javax.swing.JPanel panelSchedule;
    private javax.swing.JTable tblPatients;
    private javax.swing.JTable tblReservations;
    private javax.swing.JTable tblSchedule;
    private javax.swing.JTextField txtSearchPatient;
    // End of variables declaration//GEN-END:variables
}
