/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hospital.ui;

import com.hospital.models.*;
import com.hospital.utils.DataStore;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author lenovo
 */
public class NurseDashboard extends javax.swing.JFrame {

    private String username;
    private DataStore dataStore;
    private String assignedDoctor = "dr.juan"; // Can be configured

    public NurseDashboard(String username) {
        this.username = username;
        this.dataStore = DataStore.getInstance();
        initComponents();
        setLocationRelativeTo(null);
        lblWelcome.setText("Welcome, Nurse " + username);
        loadAllData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelAssignedPatients = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatients = new javax.swing.JTable();
        btnViewPatient = new javax.swing.JButton();
        btnRefreshPatients = new javax.swing.JButton();
        txtSearchPatient = new javax.swing.JTextField();
        btnSearchPatient = new javax.swing.JButton();
        cmbFilterStatus = new javax.swing.JComboBox();
        panelDoctorInfo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDoctorInfo = new javax.swing.JTextArea();
        btnRefreshDoctorInfo = new javax.swing.JButton();
        panelNotes = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblNotes = new javax.swing.JTable();
        btnAddNote = new javax.swing.JButton();
        btnViewNote = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Nurse Dashboard");

        lblWelcome.setBackground(new java.awt.Color(255, 255, 255));
        lblWelcome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 204, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome, Nurse");

        jTabbedPane1.setForeground(new java.awt.Color(0, 204, 204));

        tblPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Type", "Disease", "Status", "Room"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPatients);

        btnViewPatient.setBackground(new java.awt.Color(153, 153, 153));
        btnViewPatient.setText("View Details");
        btnViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientActionPerformed(evt);
            }
        });

        btnRefreshPatients.setBackground(new java.awt.Color(0, 204, 51));
        btnRefreshPatients.setText("Refresh");
        btnRefreshPatients.setPreferredSize(new java.awt.Dimension(92, 63));

        btnSearchPatient.setText("Search");
        btnSearchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPatientActionPerformed(evt);
            }
        });

        cmbFilterStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Checked In", "Under Treatment", "Critical" }));
        cmbFilterStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAssignedPatientsLayout = new javax.swing.GroupLayout(panelAssignedPatients);
        panelAssignedPatients.setLayout(panelAssignedPatientsLayout);
        panelAssignedPatientsLayout.setHorizontalGroup(
            panelAssignedPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAssignedPatientsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAssignedPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAssignedPatientsLayout.createSequentialGroup()
                        .addComponent(txtSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchPatient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFilterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAssignedPatientsLayout.createSequentialGroup()
                        .addComponent(btnViewPatient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefreshPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelAssignedPatientsLayout.setVerticalGroup(
            panelAssignedPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAssignedPatientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAssignedPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchPatient)
                    .addComponent(cmbFilterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAssignedPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshPatients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Assigned Patients", panelAssignedPatients);

        txtDoctorInfo.setColumns(20);
        txtDoctorInfo.setRows(5);
        jScrollPane4.setViewportView(txtDoctorInfo);

        btnRefreshDoctorInfo.setBackground(new java.awt.Color(0, 204, 102));
        btnRefreshDoctorInfo.setText("Refresh");

        javax.swing.GroupLayout panelDoctorInfoLayout = new javax.swing.GroupLayout(panelDoctorInfo);
        panelDoctorInfo.setLayout(panelDoctorInfoLayout);
        panelDoctorInfoLayout.setHorizontalGroup(
            panelDoctorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoctorInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDoctorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDoctorInfoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefreshDoctorInfo))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDoctorInfoLayout.setVerticalGroup(
            panelDoctorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoctorInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefreshDoctorInfo)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Doctor Information", panelDoctorInfo);

        tblNotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Last Note", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblNotes);

        btnAddNote.setBackground(new java.awt.Color(0, 204, 102));
        btnAddNote.setText("Add Note");
        btnAddNote.setPreferredSize(new java.awt.Dimension(92, 63));
        btnAddNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNoteActionPerformed(evt);
            }
        });

        btnViewNote.setBackground(new java.awt.Color(153, 153, 153));
        btnViewNote.setText("View All Notes");
        btnViewNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewNoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNotesLayout = new javax.swing.GroupLayout(panelNotes);
        panelNotes.setLayout(panelNotesLayout);
        panelNotesLayout.setHorizontalGroup(
            panelNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNotesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnViewNote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddNote, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        panelNotesLayout.setVerticalGroup(
            panelNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotesLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewNote, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Patient Notes", panelNotes);

        btnLogout.setBackground(new java.awt.Color(255, 51, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(683, 683, 683)
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientActionPerformed
        int selectedRow = tblPatients.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a patient", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String patientId = (String) tblPatients.getValueAt(selectedRow, 0);
        Patient patient = dataStore.getPatientById(patientId);

        if (patient == null) return;

        StringBuilder details = new StringBuilder();
        details.append("PATIENT DETAILS\n");
        details.append("═══════════════════════════════════\n\n");
        details.append("Patient ID: ").append(patient.getPatientId()).append("\n");
        details.append("Name: ").append(patient.getFullName()).append("\n");
        details.append("Phone: ").append(patient.getPhone()).append("\n\n");
        details.append("Type: ").append(patient.getPatientStatus()).append("\n");
        details.append("Disease: ").append(patient.getDisease()).append("\n");
        details.append("Status: ").append(patient.getStatus()).append("\n");
        details.append("Room: ").append(patient.getAssignedRoom() != null ? patient.getAssignedRoom() : "N/A").append("\n");
        details.append("Assigned Doctor: Dr. ").append(patient.getAssignedDoctor()).append("\n");

        JTextArea textArea = new JTextArea(details.toString());
        textArea.setEditable(false);
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(400, 250));

        JOptionPane.showMessageDialog(this, scrollPane, "Patient Details", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewPatientActionPerformed

    private void btnAddNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNoteActionPerformed
        int selectedRow = tblNotes.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a patient", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String patientId = (String) tblNotes.getValueAt(selectedRow, 0);
        String patientName = (String) tblNotes.getValueAt(selectedRow, 1);

        JTextArea txtNote = new JTextArea(5, 30);
        txtNote.setLineWrap(true);
        txtNote.setWrapStyleWord(true);
        JScrollPane scrollPane = new JScrollPane(txtNote);

        JPanel panel = new JPanel(new java.awt.BorderLayout());
        panel.add(new JLabel("Add care note for " + patientName + ":"), java.awt.BorderLayout.NORTH);
        panel.add(scrollPane, java.awt.BorderLayout.CENTER);

        int result = JOptionPane.showConfirmDialog(this, panel, 
            "Add Patient Note", 
            JOptionPane.OK_CANCEL_OPTION, 
            JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            String note = txtNote.getText().trim();
            if (!note.isEmpty()) {
                // In a real system, save to database
                JOptionPane.showMessageDialog(this, 
                    "Note added successfully!\n\nNote: " + note, 
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAddNoteActionPerformed

    private void btnViewNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewNoteActionPerformed
        int selectedRow = tblNotes.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a patient", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String patientName = (String) tblNotes.getValueAt(selectedRow, 1);

        StringBuilder notes = new StringBuilder();
        notes.append("PATIENT CARE NOTES - ").append(patientName).append("\n");
        notes.append("═══════════════════════════════════\n\n");
        notes.append("2026-01-10 09:00 - Vital signs checked: BP 120/80, Temp 98.6°F\n");
        notes.append("2026-01-10 13:00 - Administered prescribed medication\n");
        notes.append("2026-01-10 16:00 - Patient resting comfortably\n\n");
        notes.append("(In a real system, notes would be stored in database)\n");

        JTextArea textArea = new JTextArea(notes.toString());
        textArea.setEditable(false);
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 11));
        
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(450, 300));

        JOptionPane.showMessageDialog(this, scrollPane, "Patient Notes", JOptionPane.INFORMATION_MESSAGE);
    }

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to logout?", 
            "Confirm Logout", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnViewNoteActionPerformed

    private void btnSearchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPatientActionPerformed
       searchPatients();
    }//GEN-LAST:event_btnSearchPatientActionPerformed

    private void cmbFilterStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterStatusActionPerformed
        filterPatients();
    }//GEN-LAST:event_cmbFilterStatusActionPerformed
/**
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    */
    /**
     * @param args the command line arguments
     */
    /**public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NurseDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NurseDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NurseDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NurseDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NurseDashboard().setVisible(true);
            }
        });
    }*/
    private void loadAllData() {
        loadAssignedPatients();
        loadDoctorInfo();
        loadPatientNotes();
    }
    
    private void loadAssignedPatients() {
        DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();
        model.setRowCount(0);

        List<Patient> patients = dataStore.getPatients();
        for (Patient p : patients) {
            if (p.getAssignedDoctor().equals(assignedDoctor)) {
                model.addRow(new Object[]{
                    p.getPatientId(),
                    p.getFullName(),
                    p.getPatientStatus(),
                    p.getDisease(),
                    p.getStatus(),
                    p.getAssignedRoom() != null ? p.getAssignedRoom() : "N/A"
                });
            }
        }
    }
    
    private void searchPatients() {
        String searchText = txtSearchPatient.getText().trim().toLowerCase();
        
        DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();
        model.setRowCount(0);

        List<Patient> patients = dataStore.getPatients();
        for (Patient p : patients) {
            if (p.getAssignedDoctor().equals(assignedDoctor)) {
                if (searchText.isEmpty() ||
                    p.getPatientId().toLowerCase().contains(searchText) ||
                    p.getFullName().toLowerCase().contains(searchText)) {
                    
                    model.addRow(new Object[]{
                        p.getPatientId(),
                        p.getFullName(),
                        p.getPatientStatus(),
                        p.getDisease(),
                        p.getStatus(),
                        p.getAssignedRoom() != null ? p.getAssignedRoom() : "N/A"
                    });
                }
            }
        }
    }
    
    private void filterPatients() {
        String filter = (String) cmbFilterStatus.getSelectedItem();
        
        DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();
        model.setRowCount(0);

        List<Patient> patients = dataStore.getPatients();
        for (Patient p : patients) {
            if (p.getAssignedDoctor().equals(assignedDoctor)) {
                if (filter.equals("All") || p.getStatus().equals(filter)) {
                    model.addRow(new Object[]{
                        p.getPatientId(),
                        p.getFullName(),
                        p.getPatientStatus(),
                        p.getDisease(),
                        p.getStatus(),
                        p.getAssignedRoom() != null ? p.getAssignedRoom() : "N/A"
                    });
                }
            }
        }
    }
    
    private void loadDoctorInfo() {
        StringBuilder info = new StringBuilder();
        info.append("ASSIGNED DOCTOR INFORMATION\n");
        info.append("═══════════════════════════════════════\n\n");
        info.append("Doctor Username: ").append(assignedDoctor).append("\n");
        info.append("Role: Doctor\n\n");
        
        // Count patients
        int patientCount = 0;
        int criticalCount = 0;
        List<Patient> patients = dataStore.getPatients();
        for (Patient p : patients) {
            if (p.getAssignedDoctor().equals(assignedDoctor)) {
                patientCount++;
                if (p.getStatus().equals("Critical")) {
                    criticalCount++;
                }
            }
        }
       
        info.append("WORKLOAD SUMMARY:\n");
        info.append("─────────────────────────────────────\n");
        info.append("Total Patients: ").append(patientCount).append("\n");
        info.append("Critical Patients: ").append(criticalCount).append("\n\n");
        
        // Count reservations
        int todayReservations = 0;
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String today = sdf.format(new java.util.Date());
        
        List<Reservation> reservations = dataStore.getReservations();
        for (Reservation r : reservations) {
            if (r.getAssignedDoctor().equals(assignedDoctor) && 
                r.getDate().startsWith(today) &&
                r.getStatus().equals("Approved")) {
                todayReservations++;
            }
        }
        
        info.append("Today's Appointments: ").append(todayReservations).append("\n\n");
        
        info.append("INSTRUCTIONS:\n");
        info.append("─────────────────────────────────────\n");
        info.append("• Monitor all patients assigned to Dr. ").append(assignedDoctor).append("\n");
        info.append("• Report critical conditions immediately\n");
        info.append("• Maintain accurate patient notes\n");
        info.append("• Assist with patient care and procedures\n");
        
        txtDoctorInfo.setText(info.toString());
        txtDoctorInfo.setCaretPosition(0);
    }
    
    private void loadPatientNotes() {
        DefaultTableModel model = (DefaultTableModel) tblNotes.getModel();
        model.setRowCount(0);

        List<Patient> patients = dataStore.getPatients();
        for (Patient p : patients) {
            if (p.getAssignedDoctor().equals(assignedDoctor)) {
                model.addRow(new Object[]{
                    p.getPatientId(),
                    p.getFullName(),
                    "View notes for details",
                    new java.util.Date().toString()
                });
            }
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNote;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefreshDoctorInfo;
    private javax.swing.JButton btnRefreshPatients;
    private javax.swing.JButton btnSearchPatient;
    private javax.swing.JButton btnViewNote;
    private javax.swing.JButton btnViewPatient;
    private javax.swing.JComboBox cmbFilterStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panelAssignedPatients;
    private javax.swing.JPanel panelDoctorInfo;
    private javax.swing.JPanel panelNotes;
    private javax.swing.JTable tblNotes;
    private javax.swing.JTable tblPatients;
    private javax.swing.JTextArea txtDoctorInfo;
    private javax.swing.JTextField txtSearchPatient;
    // End of variables declaration//GEN-END:variables
}
