/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hospital.ui;

import com.hospital.models.*;
import com.hospital.utils.DataStore;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;



/**
 *
 * @author lenovo
 */
public class PatientDashboard extends javax.swing.JFrame {

    private Signup signup;
    private Patient patient;
    private DataStore dataStore;

    public PatientDashboard(Signup signup) {
        this.signup = signup;
        this.dataStore = DataStore.getInstance();
        this.patient = dataStore.getPatientById(signup.getPatientId());
        
        initComponents();
        setLocationRelativeTo(null);
        loadPatientInfo();
        loadReservations();
        loadBilling();
        checkNotifications();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelMyInfo = new javax.swing.JPanel();
        lblPatientIdLabel = new javax.swing.JLabel();
        lblPatientId = new javax.swing.JLabel();
        lblNameLabel = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmailLabel = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhoneLabel = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblStatusLabel = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDiseaseLabel = new javax.swing.JLabel();
        lblDisease = new javax.swing.JLabel();
        lblDoctorLabel = new javax.swing.JLabel();
        lblDoctor = new javax.swing.JLabel();
        lblRoomLabel = new javax.swing.JLabel();
        lblRoom = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelReservations = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservations = new javax.swing.JTable();
        btnMakeReservation = new javax.swing.JButton();
        btnViewReservationDetails = new javax.swing.JButton();
        btnCancelReservation = new javax.swing.JButton();
        btnRefreshReservations = new javax.swing.JButton();
        cmbReservationFilter = new javax.swing.JComboBox();
        btnFilterReservations = new javax.swing.JButton();
        panelBilling = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBilling = new javax.swing.JTable();
        panelNotifications = new javax.swing.JPanel();
        lblNotificationTitle = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPaneNotifications = new javax.swing.JScrollPane();
        txtNotifications = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Patient Portal");

        lblWelcome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 204, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome");

        btnLogout.setBackground(new java.awt.Color(255, 51, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jTabbedPane1.setForeground(new java.awt.Color(0, 204, 204));
        jTabbedPane1.setOpaque(true);

        lblPatientIdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPatientIdLabel.setText("Patient ID:");

        lblPatientId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPatientId.setText("-");

        lblNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNameLabel.setText("Name:");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblName.setText("-");

        lblEmailLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmailLabel.setText("Email:");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setText("-");

        lblPhoneLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPhoneLabel.setText("Phone:");

        lblPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPhone.setText("-");

        lblStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblStatusLabel.setText("Status:");

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblStatus.setText("-");

        lblDiseaseLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiseaseLabel.setText("Diagnosis:");

        lblDisease.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDisease.setText("-");

        lblDoctorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDoctorLabel.setText("Doctor:");

        lblDoctor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDoctor.setText("-");

        lblRoomLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRoomLabel.setText("Room:");

        lblRoom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRoom.setText("-");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MY INFORMATIONS");

        javax.swing.GroupLayout panelMyInfoLayout = new javax.swing.GroupLayout(panelMyInfo);
        panelMyInfo.setLayout(panelMyInfoLayout);
        panelMyInfoLayout.setHorizontalGroup(
            panelMyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMyInfoLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addGroup(panelMyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPatientIdLabel)
                    .addComponent(lblNameLabel)
                    .addComponent(lblEmailLabel)
                    .addComponent(lblPhoneLabel)
                    .addComponent(lblStatusLabel)
                    .addComponent(lblDiseaseLabel)
                    .addComponent(lblDoctorLabel)
                    .addComponent(lblRoomLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(lblDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDisease, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPatientId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        panelMyInfoLayout.setVerticalGroup(
            panelMyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMyInfoLayout.createSequentialGroup()
                .addGroup(panelMyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMyInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(panelMyInfoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(panelMyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientIdLabel)
                            .addComponent(lblPatientId))))
                .addGap(18, 18, 18)
                .addGroup(panelMyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMyInfoLayout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmail))
                    .addGroup(panelMyInfoLayout.createSequentialGroup()
                        .addComponent(lblNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmailLabel)))
                .addGap(18, 18, 18)
                .addGroup(panelMyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoneLabel)
                    .addComponent(lblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatusLabel)
                    .addComponent(lblStatus))
                .addGap(18, 18, 18)
                .addGroup(panelMyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisease)
                    .addComponent(lblDiseaseLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctor)
                    .addComponent(lblDoctorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoom)
                    .addComponent(lblRoomLabel))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Information", panelMyInfo);

        tblReservations.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Type", "Doctor", "Date", "Status", "Notes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReservations);

        btnMakeReservation.setBackground(new java.awt.Color(255, 153, 0));
        btnMakeReservation.setText("Make New Reservation");
        btnMakeReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeReservationActionPerformed(evt);
            }
        });

        btnViewReservationDetails.setBackground(new java.awt.Color(153, 153, 153));
        btnViewReservationDetails.setText("View Details");
        btnViewReservationDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReservationDetailsActionPerformed(evt);
            }
        });

        btnCancelReservation.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelReservation.setText("Cancel Reservation");
        btnCancelReservation.setPreferredSize(new java.awt.Dimension(92, 63));
        btnCancelReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelReservationActionPerformed(evt);
            }
        });

        btnRefreshReservations.setBackground(new java.awt.Color(51, 204, 0));
        btnRefreshReservations.setText("Refresh");

        cmbReservationFilter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Reservations", "Upcoming Only", "Past Only ", "Pending Approval", "Approved", "Cancelled/Declined" }));
        cmbReservationFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbReservationFilterActionPerformed(evt);
            }
        });

        btnFilterReservations.setBackground(new java.awt.Color(0, 204, 0));
        btnFilterReservations.setText("Apply Filter");
        btnFilterReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterReservationsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReservationsLayout = new javax.swing.GroupLayout(panelReservations);
        panelReservations.setLayout(panelReservationsLayout);
        panelReservationsLayout.setHorizontalGroup(
            panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(panelReservationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservationsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmbReservationFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFilterReservations))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservationsLayout.createSequentialGroup()
                        .addComponent(btnViewReservationDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                        .addComponent(btnMakeReservation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefreshReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelReservationsLayout.setVerticalGroup(
            panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbReservationFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilterReservations))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMakeReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewReservationDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Reservations", panelReservations);

        tblBilling.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblBilling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bill ID", "Description", "Amount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblBilling);

        javax.swing.GroupLayout panelBillingLayout = new javax.swing.GroupLayout(panelBilling);
        panelBilling.setLayout(panelBillingLayout);
        panelBillingLayout.setHorizontalGroup(
            panelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
        );
        panelBillingLayout.setVerticalGroup(
            panelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillingLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Billing", panelBilling);

        lblNotificationTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNotificationTitle.setForeground(new java.awt.Color(255, 102, 0));
        lblNotificationTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotificationTitle.setText("Notifications & Reminders");

        txtNotifications.setColumns(20);
        txtNotifications.setRows(5);
        jScrollPaneNotifications.setViewportView(txtNotifications);

        jScrollPane4.setViewportView(jScrollPaneNotifications);

        javax.swing.GroupLayout panelNotificationsLayout = new javax.swing.GroupLayout(panelNotifications);
        panelNotifications.setLayout(panelNotificationsLayout);
        panelNotificationsLayout.setHorizontalGroup(
            panelNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNotificationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
        );
        panelNotificationsLayout.setVerticalGroup(
            panelNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotificationsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblNotificationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        jTabbedPane1.addTab("Notification", panelNotifications);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jTabbedPane1)
            .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to logout?", 
        "Confirm Logout", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnFilterReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterReservationsActionPerformed
        filterReservations();
    }//GEN-LAST:event_btnFilterReservationsActionPerformed

    private void cmbReservationFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbReservationFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbReservationFilterActionPerformed

    private void btnCancelReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelReservationActionPerformed
        int selectedRow = tblReservations.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select a reservation to cancel",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String resId = (String) tblReservations.getValueAt(selectedRow, 0);
        String status = (String) tblReservations.getValueAt(selectedRow, 4);

        // Check if reservation can be cancelled
        if (status.equals("Declined") || status.equals("Cancelled")) {
            JOptionPane.showMessageDialog(this,
                "This reservation is already " + status.toLowerCase(),
                "Cannot Cancel", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Find reservation
        Reservation reservation = null;
        for (Reservation r : dataStore.getReservations()) {
            if (r.getReservationId().equals(resId)) {
                reservation = r;
                break;
            }
        }

        if (reservation == null) {
            JOptionPane.showMessageDialog(this,
                "Reservation not found",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if it's too late to cancel (within 24 hours)
        try {
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm");
            java.util.Date resDate = sdf.parse(reservation.getDate());
            java.util.Date now = new java.util.Date();

            long diffMillis = resDate.getTime() - now.getTime();
            long diffHours = diffMillis / (60 * 60 * 1000);

            if (diffHours < 24 && diffHours > 0) {
                int confirm = JOptionPane.showConfirmDialog(this,
                    "Your reservation is within 24 hours.\n" +
                    "Late cancellation may incur charges.\n\n" +
                    "Do you still want to cancel?",
                    "Late Cancellation",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

                if (confirm != JOptionPane.YES_OPTION) {
                    return;
                }
            }
        } catch (Exception e) {
            // Continue with cancellation if date parsing fails
        }

        // Confirm cancellation
        String reason = JOptionPane.showInputDialog(this,
            "Please provide a reason for cancellation (optional):",
            "Cancel Reservation",
            JOptionPane.QUESTION_MESSAGE);

        if (reason == null) { // User clicked cancel
            return;
        }

        // Update reservation status
        reservation.setStatus("Cancelled");
        if (!reason.trim().isEmpty()) {
            String existingNotes = reservation.getNotes();
            reservation.setNotes(existingNotes + "\nCancellation reason: " + reason);
        }

        JOptionPane.showMessageDialog(this,
            "Reservation cancelled successfully.\n" +
            "Reservation ID: " + resId,
            "Cancelled",
            JOptionPane.INFORMATION_MESSAGE);

        loadReservations();
    }//GEN-LAST:event_btnCancelReservationActionPerformed

    private void btnViewReservationDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReservationDetailsActionPerformed
        int selectedRow = tblReservations.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select a reservation to view",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String resId = (String) tblReservations.getValueAt(selectedRow, 0);

        // Find reservation
        Reservation reservation = null;
        for (Reservation r : dataStore.getReservations()) {
            if (r.getReservationId().equals(resId)) {
                reservation = r;
                break;
            }
        }

        if (reservation == null) {
            JOptionPane.showMessageDialog(this,
                "Reservation not found",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create details dialog
        StringBuilder details = new StringBuilder();
        details.append("RESERVATION DETAILS\n");
        details.append("═══════════════════════════════════\n\n");
        details.append("Reservation ID: ").append(reservation.getReservationId()).append("\n");
        details.append("Patient ID: ").append(reservation.getPatientId()).append("\n");
        details.append("Patient Name: ").append(patient.getFullName()).append("\n\n");
        details.append("Type: ").append(reservation.getType()).append("\n");
        details.append("Assigned Doctor: ").append(reservation.getAssignedDoctor()).append("\n");
        details.append("Date & Time: ").append(reservation.getDate()).append("\n\n");
        details.append("Status: ").append(reservation.getStatus()).append("\n");
        details.append("Notes: ").append(reservation.getNotes().isEmpty() ? "None" : reservation.getNotes()).append("\n\n");

        // Add status-specific messages
        if (reservation.getStatus().equals("Pending")) {
            details.append("⏳ Waiting for admin approval\n");
        } else if (reservation.getStatus().equals("Approved")) {
            details.append("✓ Your reservation has been approved!\n");
            details.append("  Please arrive 15 minutes early.\n");
        } else if (reservation.getStatus().equals("Declined")) {
            details.append("✗ Reservation was declined\n");
        } else if (reservation.getStatus().equals("Cancelled")) {
            details.append("✗ You cancelled this reservation\n");
        }

        int choice = JOptionPane.showConfirmDialog(this,
            "Would you like to print a confirmation?",
            "Print Confirmation",
            JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION && reservation != null) {
            printReservationConfirmation(reservation);
        }

        JTextArea textArea = new JTextArea(details.toString());
        textArea.setEditable(false);
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        textArea.setRows(15);
        textArea.setColumns(40);

        JScrollPane scrollPane = new JScrollPane(textArea);

        JOptionPane.showMessageDialog(this,
            scrollPane,
            "Reservation Details",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewReservationDetailsActionPerformed

    private void btnMakeReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeReservationActionPerformed
        if (patient == null) {
            JOptionPane.showMessageDialog(this,
                "Patient information not found. Please re-login.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create reservation dialog with all options
        JPanel panel = new JPanel(new java.awt.GridLayout(6, 2, 10, 10));

        JComboBox<String> cmbType = new JComboBox<String>(new String[]{
            "Check-up",
            "Admission",
            "Follow-up",
            "Emergency",
            "Consultation"
        });

        JComboBox<String> cmbDoctor = new JComboBox<String>();
        // Populate with available doctors
        List<User> users = dataStore.getUsers();
        for (User u : users) {
            if (u.getRole().equals("DOCTOR")) {
                cmbDoctor.addItem(u.getUsername());
            }
        }

        // Date selection
        JComboBox<String> cmbYear = new JComboBox<String>();
        JComboBox<String> cmbMonth = new JComboBox<String>();
        JComboBox<String> cmbDay = new JComboBox<String>();

        // Populate year (current year and next year)
        java.util.Calendar cal = java.util.Calendar.getInstance();
        int currentYear = cal.get(java.util.Calendar.YEAR);
        cmbYear.addItem(String.valueOf(currentYear));
        cmbYear.addItem(String.valueOf(currentYear + 1));

        // Populate months
        String[] months = {"01", "02", "03", "04", "05", "06",
            "07", "08", "09", "10", "11", "12"};
        for (String month : months) {
            cmbMonth.addItem(month);
        }

        // Populate days
        for (int i = 1; i <= 31; i++) {
            cmbDay.addItem(String.format("%02d", i));
        }

        // Set current date as default
        cmbMonth.setSelectedIndex(cal.get(java.util.Calendar.MONTH));
        cmbDay.setSelectedIndex(cal.get(java.util.Calendar.DAY_OF_MONTH) - 1);

        // Time selection
        JComboBox<String> cmbHour = new JComboBox<String>();
        for (int i = 8; i <= 17; i++) { // 8 AM to 5 PM
            cmbHour.addItem(String.format("%02d", i));
        }

        JComboBox<String> cmbMinute = new JComboBox<String>(
            new String[]{"00", "15", "30", "45"}
        );

        JTextArea txtReason = new JTextArea(3, 20);
        txtReason.setLineWrap(true);
        txtReason.setWrapStyleWord(true);
        JScrollPane scrollReason = new JScrollPane(txtReason);

        // Add components to panel
        panel.add(new JLabel("Reservation Type:"));
        panel.add(cmbType);

        panel.add(new JLabel("Preferred Doctor:"));
        panel.add(cmbDoctor);

        JPanel datePanel = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        datePanel.add(cmbYear);
        datePanel.add(new JLabel("-"));
        datePanel.add(cmbMonth);
        datePanel.add(new JLabel("-"));
        datePanel.add(cmbDay);
        panel.add(new JLabel("Date:"));
        panel.add(datePanel);

        JPanel timePanel = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        timePanel.add(cmbHour);
        timePanel.add(new JLabel(":"));
        timePanel.add(cmbMinute);
        panel.add(new JLabel("Time:"));
        panel.add(timePanel);

        panel.add(new JLabel("Reason/Symptoms:"));
        panel.add(scrollReason);

        panel.add(new JLabel("")); // Spacer
        JLabel lblNote = new JLabel("<html><i>* Admin approval required</i></html>");
        lblNote.setFont(new java.awt.Font("Dialog", java.awt.Font.ITALIC, 11));
        panel.add(lblNote);

        int result = JOptionPane.showConfirmDialog(this, panel,
            "Make New Reservation",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            // Validate inputs
            if (cmbDoctor.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this,
                    "Please select a doctor",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String reason = txtReason.getText().trim();
            if (reason.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Please provide a reason for your visit",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Build date string
            String date = cmbYear.getSelectedItem() + "-" +
            cmbMonth.getSelectedItem() + "-" +
            cmbDay.getSelectedItem();

            String time = cmbHour.getSelectedItem() + ":" +
            cmbMinute.getSelectedItem();

            String dateTime = date + " " + time;

            // Validate date is not in the past
            try {
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm");
                java.util.Date selectedDate = sdf.parse(dateTime);
                java.util.Date now = new java.util.Date();

                if (selectedDate.before(now)) {
                    JOptionPane.showMessageDialog(this,
                        "Cannot make reservation for past date/time",
                        "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Invalid date/time",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check for conflicting reservations (same patient, same day)
            List<Reservation> existingRes = dataStore.getReservations();
            for (Reservation r : existingRes) {
                if (r.getPatientId().equals(patient.getPatientId()) &&
                    r.getDate().startsWith(date) &&
                    !r.getStatus().equals("Declined") &&
                    !r.getStatus().equals("Cancelled")) {

                    int confirm = JOptionPane.showConfirmDialog(this,
                        "You already have a reservation on " + date + ".\nDo you want to continue?",
                        "Existing Reservation",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE);

                    if (confirm != JOptionPane.YES_OPTION) {
                        return;
                    }
                    break;
                }
            }

            // Generate Reservation ID
            String resId = "RES" + String.format("%03d", dataStore.getReservations().size() + 1);

            // Create reservation
            Reservation newRes = new Reservation(
                resId,
                patient.getPatientId(),
                (String) cmbType.getSelectedItem(),
                (String) cmbDoctor.getSelectedItem(),
                dateTime,
                "Pending",
                "Reason: " + reason
            );

            dataStore.getReservations().add(newRes);

            // Show confirmation
            JOptionPane.showMessageDialog(this,
                "Reservation created successfully!\n\n" +
                "Reservation ID: " + resId + "\n" +
                "Type: " + cmbType.getSelectedItem() + "\n" +
                "Doctor: " + cmbDoctor.getSelectedItem() + "\n" +
                "Date & Time: " + dateTime + "\n\n" +
                "Status: Pending Admin Approval",
                "Reservation Created",
                JOptionPane.INFORMATION_MESSAGE);

            loadReservations();
        }
    }//GEN-LAST:event_btnMakeReservationActionPerformed
    
    
private void printReservationConfirmation(Reservation reservation) {
    StringBuilder confirmation = new StringBuilder();
    
    confirmation.append("\n");
    confirmation.append("╔════════════════════════════════════════════════════╗\n");
    confirmation.append("║       HOSPITAL RESERVATION CONFIRMATION           ║\n");
    confirmation.append("╚════════════════════════════════════════════════════╝\n\n");
    
    confirmation.append("Reservation ID: ").append(reservation.getReservationId()).append("\n");
    confirmation.append("Date Generated: ").append(new java.util.Date().toString()).append("\n\n");
    
    confirmation.append("PATIENT INFORMATION:\n");
    confirmation.append("─────────────────────────────────────────────────────\n");
    confirmation.append("Patient ID: ").append(patient.getPatientId()).append("\n");
    confirmation.append("Name: ").append(patient.getFullName()).append("\n");
    confirmation.append("Phone: ").append(patient.getPhone()).append("\n");
    confirmation.append("Email: ").append(patient.getEmail()).append("\n\n");
    
    confirmation.append("APPOINTMENT DETAILS:\n");
    confirmation.append("─────────────────────────────────────────────────────\n");
    confirmation.append("Type: ").append(reservation.getType()).append("\n");
    confirmation.append("Doctor: Dr. ").append(reservation.getAssignedDoctor()).append("\n");
    confirmation.append("Date & Time: ").append(reservation.getDate()).append("\n");
    confirmation.append("Status: ").append(reservation.getStatus()).append("\n");
    confirmation.append("Notes: ").append(reservation.getNotes()).append("\n\n");
    
    confirmation.append("IMPORTANT REMINDERS:\n");
    confirmation.append("─────────────────────────────────────────────────────\n");
    confirmation.append("• Please arrive 15 minutes before your appointment\n");
    confirmation.append("• Bring a valid ID and insurance card (if applicable)\n");
    confirmation.append("• Cancel at least 24 hours in advance if needed\n");
    confirmation.append("• Contact us at hospital@example.com for questions\n\n");
    
    confirmation.append("Thank you for choosing our hospital!\n");
    confirmation.append("════════════════════════════════════════════════════\n");
    
    // Display and offer to save
    JTextArea textArea = new JTextArea(confirmation.toString());
    textArea.setEditable(false);
    textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 11));
    
    JScrollPane scrollPane = new JScrollPane(textArea);
    scrollPane.setPreferredSize(new java.awt.Dimension(500, 400));
    
    int choice = JOptionPane.showOptionDialog(this, 
        scrollPane,
        "Reservation Confirmation", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.INFORMATION_MESSAGE,
        null,
        new String[]{"Save to File", "Close"},
        "Close");
    
    if (choice == 0) { // Save to file
        try {
            String filename = "reservation_" + reservation.getReservationId() + ".txt";
            java.io.FileWriter writer = new java.io.FileWriter(filename);
            writer.write(confirmation.toString());
            writer.close();
            JOptionPane.showMessageDialog(this, 
                "Confirmation saved to: " + filename, 
                "Saved", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error saving file: " + e.getMessage(), 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
    
    private void filterReservations() {
    if (patient == null) return;
    
    String filter = (String) cmbReservationFilter.getSelectedItem();
    
    DefaultTableModel model = (DefaultTableModel) tblReservations.getModel();
    model.setRowCount(0);

    List<Reservation> reservations = dataStore.getReservations();
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm");
    java.util.Date now = new java.util.Date();
    
    for (Reservation r : reservations) {
        if (!r.getPatientId().equals(patient.getPatientId())) continue;
        
        boolean include = false;
        
        try {
            java.util.Date resDate = sdf.parse(r.getDate());
            boolean isFuture = resDate.after(now);
            
            if (filter.equals("All Reservations")) {
                include = true;
            } else if (filter.equals("Upcoming Only") && isFuture) {
                include = true;
            } else if (filter.equals("Past Only") && !isFuture) {
                include = true;
            } else if (filter.equals("Pending Approval") && r.getStatus().equals("Pending")) {
                include = true;
            } else if (filter.equals("Approved") && r.getStatus().equals("Approved")) {
                include = true;
            } else if (filter.equals("Cancelled/Declined") && 
                      (r.getStatus().equals("Cancelled") || r.getStatus().equals("Declined"))) {
                include = true;
            }
        } catch (Exception e) {
            include = filter.equals("All Reservations");
        }
        
        if (include) {
            model.addRow(new Object[]{
                r.getReservationId(),
                r.getType(),
                r.getAssignedDoctor(),
                r.getDate(),
                r.getStatus(),
                r.getNotes()
            });
        }
    }
    
    // Apply color coding
    tblReservations.getColumnModel().getColumn(4).setCellRenderer(
        new javax.swing.table.DefaultTableCellRenderer() {
            public java.awt.Component getTableCellRendererComponent(
                javax.swing.JTable table, Object value, boolean isSelected, 
                boolean hasFocus, int row, int column) {
                
                java.awt.Component c = super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);
                
                if (!isSelected) {
                    String status = (String) value;
                    if (status.equals("Approved")) {
                        c.setBackground(new java.awt.Color(200, 255, 200));
                    } else if (status.equals("Pending")) {
                        c.setBackground(new java.awt.Color(255, 255, 200));
                    } else if (status.equals("Declined") || status.equals("Cancelled")) {
                        c.setBackground(new java.awt.Color(255, 200, 200));
                    } else {
                        c.setBackground(java.awt.Color.WHITE);
                    }
                } else {
                    c.setBackground(table.getSelectionBackground());
                }
                
                return c;
            }
        }
    );
    }
    
    private void checkNotifications() {
    if (patient == null) return;
    
    StringBuilder notifications = new StringBuilder();
    int notificationCount = 0;
    
    // Check for upcoming reservations
    List<Reservation> reservations = dataStore.getReservations();
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm");
    java.util.Date now = new java.util.Date();
    
    for (Reservation r : reservations) {
        if (!r.getPatientId().equals(patient.getPatientId())) continue;
        
        try {
            java.util.Date resDate = sdf.parse(r.getDate());
            long diffMillis = resDate.getTime() - now.getTime();
            long diffHours = diffMillis / (60 * 60 * 1000);
            long diffDays = diffMillis / (24 * 60 * 60 * 1000);
            
            if (diffHours > 0 && diffHours <= 24 && r.getStatus().equals("Approved")) {
                // Within 24 hours
                notificationCount++;
                notifications.append("⏰ REMINDER: You have a ").append(r.getType())
                    .append(" appointment with Dr. ").append(r.getAssignedDoctor())
                    .append(" in ").append(diffHours).append(" hour(s)! ");
            } else if (diffDays >= 0 && diffDays <= 3 && r.getStatus().equals("Approved")) {
                // Within 3 days
                notificationCount++;
                notifications.append("📅 Upcoming: ").append(r.getType())
                    .append(" with Dr. ").append(r.getAssignedDoctor())
                    .append(" on ").append(r.getDate()).append(". ");
            } else if (r.getStatus().equals("Pending")) {
                // Pending approval
                notificationCount++;
                notifications.append("⏳ Your ").append(r.getType())
                    .append(" reservation (ID: ").append(r.getReservationId())
                    .append(") is awaiting admin approval. ");
            } else if (r.getStatus().equals("Declined")) {
                // Recently declined
                notificationCount++;
                notifications.append("❌ Your ").append(r.getType())
                    .append(" reservation (ID: ").append(r.getReservationId())
                    .append(") was declined. ");
            }
        } catch (Exception e) {
            // Skip invalid dates
        }
    }
    
    // Check for unpaid bills
    List<Billing> billings = dataStore.getBillings();
    double unpaidTotal = 0.0;
    int unpaidCount = 0;
    
    for (Billing b : billings) {
        if (b.getPatientId().equals(patient.getPatientId()) && 
            b.getStatus().equals("Unpaid")) {
            unpaidTotal += b.getAmount();
            unpaidCount++;
        }
    }
    
    if (unpaidCount > 0) {
        notificationCount++;
        notifications.append("💰 You have ").append(unpaidCount)
            .append(" unpaid bill(s) totaling Php")
            .append(String.format("%.2f", unpaidTotal)).append(". ");
    }
    
    // Display notifications
    if (notificationCount == 0) {
        txtNotifications.setText("✓ No notifications at this time. You're all caught up!");
        panelNotifications.setBackground(new java.awt.Color(230, 255, 230)); // Light green
        panelNotifications.setBorder(javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(100, 200, 100), 2));
    } else {
        txtNotifications.setText(notifications.toString());
        panelNotifications.setBackground(new java.awt.Color(255, 250, 205)); // Light yellow
        panelNotifications.setBorder(javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(255, 200, 0), 2));
        
        // Update title with count
        lblNotificationTitle.setText("📋 Notifications & Reminders (" + notificationCount + ")");
    }
    }
    
    private void loadPatientInfo() {
        if (patient != null) {
            lblWelcome.setText("Welcome, " + patient.getFullName());
            lblPatientId.setText(patient.getPatientId());
            lblName.setText(patient.getFullName());
            lblEmail.setText(patient.getEmail());
            lblPhone.setText(patient.getPhone());
            lblStatus.setText(patient.getPatientStatus());
            lblDisease.setText(patient.getDisease());
            lblDoctor.setText(patient.getAssignedDoctor());
            lblRoom.setText(patient.getAssignedRoom() != null ? patient.getAssignedRoom() : "N/A");
        }
    }
    
    private void loadReservations() {
    DefaultTableModel model = (DefaultTableModel) tblReservations.getModel();
    model.setRowCount(0);

    if (patient == null) return;

    List<Reservation> reservations = dataStore.getReservations();
    for (Reservation r : reservations) {
        if (r.getPatientId().equals(patient.getPatientId())) {
            model.addRow(new Object[]{
                r.getReservationId(),
                r.getType(),
                r.getAssignedDoctor(),
                r.getDate(),
                r.getStatus(),
                r.getNotes()
            });
        }
    }
    
    // Add a custom renderer for status column (optional - for visual enhancement)
    tblReservations.getColumnModel().getColumn(4).setCellRenderer(
        new javax.swing.table.DefaultTableCellRenderer() {
            public java.awt.Component getTableCellRendererComponent(
                javax.swing.JTable table, Object value, boolean isSelected, 
                boolean hasFocus, int row, int column) {
                
                java.awt.Component c = super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);
                
                if (!isSelected) {
                    String status = (String) value;
                    if (status.equals("Approved")) {
                        c.setBackground(new java.awt.Color(200, 255, 200)); // Light green
                    } else if (status.equals("Pending")) {
                        c.setBackground(new java.awt.Color(255, 255, 200)); // Light yellow
                    } else if (status.equals("Declined") || status.equals("Cancelled")) {
                        c.setBackground(new java.awt.Color(255, 200, 200)); // Light red
                    } else {
                        c.setBackground(java.awt.Color.WHITE);
                    }
                } else {
                    c.setBackground(table.getSelectionBackground());
                }
                
                return c;
            }
        }
    );
}
    
    private void loadBilling() {
        DefaultTableModel model = (DefaultTableModel) tblBilling.getModel();
        model.setRowCount(0);

        if (patient == null) return;

        List<Billing> billings = dataStore.getBillings();
        for (Billing b : billings) {
            if (b.getPatientId().equals(patient.getPatientId())) {
                model.addRow(new Object[]{
                    b.getBillingId(),
                    b.getDescription(),
                    b.getAmount(),
                    b.getStatus()
                });
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    /**
    public static void main(String args[]) {
     
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDashboard().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelReservation;
    private javax.swing.JButton btnFilterReservations;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMakeReservation;
    private javax.swing.JButton btnRefreshReservations;
    private javax.swing.JButton btnViewReservationDetails;
    private javax.swing.JComboBox cmbReservationFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPaneNotifications;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDisease;
    private javax.swing.JLabel lblDiseaseLabel;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblDoctorLabel;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailLabel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameLabel;
    private javax.swing.JLabel lblNotificationTitle;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPatientIdLabel;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneLabel;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblRoomLabel;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusLabel;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panelBilling;
    private javax.swing.JPanel panelMyInfo;
    private javax.swing.JPanel panelNotifications;
    private javax.swing.JPanel panelReservations;
    private javax.swing.JTable tblBilling;
    private javax.swing.JTable tblReservations;
    private javax.swing.JTextArea txtNotifications;
    // End of variables declaration//GEN-END:variables
}
